"""Regenerate astrodeck/catalog/data/constellations.tsv from CATALOG.

WHY A SIDECAR, NOT A COLUMN IN ngc.tsv, NOT A GENERATED .py MODULE.

  * Not a new column in ngc.tsv: that file is a straight extract of OpenNGC
    (see build_ngc_catalog.py, which this repo does not let this task touch —
    it lives under server/tools/, out of astrodeck/catalog/ scope). Splicing a
    derived column into a vendored extract would blur "what OpenNGC published"
    with "what we computed from it", and the 64 hand-written curated rows in
    objects.py have no tsv row to add a column to at all — a sidecar is the
    only shape that covers BOTH sources uniformly, keyed by the same ``id``
    ``objects.CATALOG`` already uses.
  * Not a generated .py module (a dict literal): a 13,370-entry Python literal
    is ~120 KB of source that diffs as a wall of text and that every tool
    treats as code (linted, `python -m py_compile`d, etc.) for data that is
    not code. A tab-separated sidecar loads exactly like ngc.tsv already does
    (open once at import, one split per line) and diffs one line per changed
    object.

WHY PRECOMPUTED AT ALL. ``astropy.coordinates.get_constellation`` precesses
J2000 -> B1875 and tests the IAU/Delporte boundaries — correct, but not free:
looping it object-by-object over the 13,370-row catalog takes ~30s (measured).
The Atlas viewport and a camera-frame region query both call the region lookup
on every pan/zoom/frame, so a per-request cost anywhere near that is a
non-starter. Vectorising the SAME astropy call over one SkyCoord array of all
13,370 positions takes ~20ms — cheap enough to run once here, expensive enough
that "once" has to mean "at build time," not "on import," and certainly not
"per request." The runtime side (constellations.py) is a dict built from a
flat-file read: O(n) string split, no astropy import, no network.

THE EPOCH TRAP THIS SCRIPT AVOIDS. The catalog's ra_hours/dec_deg are J2000
(ICRS-frame), but the IAU constellation boundaries are defined for B1875.
``get_constellation`` DOES precess for you — but only if the ``SkyCoord`` you
hand it carries a real frame astropy can transform (``frame="icrs"`` here).
Construct the coordinate any other way — e.g. build an FK4/B1875 frame
directly from the J2000 numbers, which is what happens if the "current epoch"
is assumed instead of transformed — and boundary objects resolve to the WRONG
constellation silently (no exception, just a different name). Measured on this
catalog: skipping the precession step (matching J2000 coordinates straight
against B1875 boundaries) flips 1,127 of 13,369 objects — 8.4% of the
catalog — including IC 1, which is why that object is the epoch spot-check in
tests/test_catalog_constellations.py.

A STRAY-WHITESPACE TRAP FOUND WHILE WRITING THIS. astropy's own constellation
name table returns "Crux " (trailing space) for the Southern Cross — a known
quirk in the abbreviation-to-full-name lookup, not a boundary bug. Every name
is ``.strip()``-ed before it is written; a downstream ``describe()`` comparing
strings ("in Crux" vs "in Crux ") would otherwise fail for one specific
constellation in a way that is easy to miss in a manual spot-check.

Run from the ``server/`` directory (so the ``astrodeck`` package import
resolves):

    python -m astrodeck.catalog.build_constellations

Output is deterministic (rows sorted by id), so a rebuild diffs cleanly.
Re-run this whenever CATALOG's positions change (a new OpenNGC pull, edits to
the curated rows in objects.py) — nothing checks staleness automatically.
"""
from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).with_name("data") / "constellations.tsv"


def main() -> int:
    import astropy.units as u
    from astropy.coordinates import SkyCoord, get_constellation

    from .objects import CATALOG

    ra_deg = [o.ra_hours * 15.0 for o in CATALOG]
    dec_deg = [o.dec_deg for o in CATALOG]
    coords = SkyCoord(ra=ra_deg * u.deg, dec=dec_deg * u.deg, frame="icrs")
    names = get_constellation(coords)  # vectorised: one precession, not 13,370

    rows = sorted(zip((o.id for o in CATALOG), (str(n).strip() for n in names)))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="") as fh:
        fh.write("# Generated by build_constellations.py — do not hand-edit.\n")
        fh.write("# Regenerate: python -m astrodeck.catalog.build_constellations\n")
        fh.write("# id\tconstellation\n")
        for ident, name in rows:
            fh.write(f"{ident}\t{name}\n")
    print(f"wrote {len(rows)} constellations to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
