import assert from 'node:assert/strict';
import { AIM_CONE_DEG, DEG, DOME_CELLS, SkyPanorama, cameraLens, dot, lookBasis, orientationBasis, projectRay, skyAngles, skyVector, targetCell, unit, type CameraBasis, type DomeCell, type V3 } from '../photosphereGeometry';
import { traceSkyCoverage } from '../photosphere';
let passed=0;
function test(name:string,fn:()=>void){fn();passed++;console.log(`PASS ${name}`);}
const near=(a:number,b:number,tolerance=.001)=>assert.ok(Math.abs(a-b)<tolerance,`${a} != ${b}`);
test('Independent physical poses put east at image-right and up at image-top',()=>{
  // Expected earth axes are specified directly, not generated by lookBasis.
  for(const [alpha,beta,gamma,screen] of [[0,90,0,0],[90,0,-90,90],[270,0,90,270],[180,-90,0,180]]){
    const b=orientationBasis(alpha,beta,gamma,screen);
    b.right.forEach((n,i)=>near(n,[1,0,0][i]));
    b.up.forEach((n,i)=>near(n,[0,0,1][i]));
    b.forward.forEach((n,i)=>near(n,[0,1,0][i]));
  }
  const east=orientationBasis(270,90,0);
  east.forward.forEach((n,i)=>near(n,[1,0,0][i]));
  east.right.forEach((n,i)=>near(n,[0,-1,0][i]));
});
test('Known image landmarks land at their bearings and heights, including both sides of north',()=>{
  const w=240,h=320,data=new Uint8ClampedArray(w*h*4).fill(40);
  // Portrait short axis = horizontal 60 degrees. Independent pinhole formula.
  const focal=w/(2*Math.tan(Math.PI/6));
  const marks=[{az:0,alt:0,rgb:[255,0,0]},{az:15,alt:0,rgb:[0,255,0]},{az:0,alt:20,rgb:[0,0,255]}];
  for(const mark of marks){
    const a=mark.az*Math.PI/180,b=mark.alt*Math.PI/180;
    const x=w/2+focal*Math.tan(a),y=h/2-focal*Math.tan(b)/Math.cos(a);
    for(let yy=Math.round(y)-4;yy<=Math.round(y)+4;yy++)for(let xx=Math.round(x)-4;xx<=Math.round(x)+4;xx++)data.set([...mark.rgb,255],(yy*w+xx)*4);
  }
  const panorama=new SkyPanorama(720,301);
  panorama.add(data,w,h,orientationBasis(0,90,0));
  const pixel=(az:number,alt:number)=>{
    const x=Math.floor(((az+360)%360)/360*720),y=Math.round((90-alt)*3);
    return [...panorama.pixels.slice((y*720+x)*4,(y*720+x)*4+3)];
  };
  for(const mark of marks)assert.deepEqual(pixel(mark.az,mark.alt),mark.rgb);
  assert.deepEqual(pixel(359.5,0),[255,0,0]);
  assert.deepEqual(pixel(.5,0),[255,0,0]);
});
test('Off-centre overhead capture samples zenith, not the centre, and later frames cannot erase it',()=>{
  const w=120,h=160,data=new Uint8ClampedArray(w*h*4).fill(220);
  // Camera is 5 degrees below vertical. Zenith lies above image centre.
  const y=Math.floor(h/2-(w/(2*Math.tan(Math.PI/6)))*Math.tan(5*Math.PI/180));
  data.set([11,22,33,255],(y*w+w/2)*4);
  const panorama=new SkyPanorama(360,101);
  panorama.addZenith(data,w,h,orientationBasis(0,175,0));
  assert.deepEqual([...panorama.pixels.slice(0,4)],[11,22,33,255]);
  panorama.add(new Uint8ClampedArray(w*h*4).fill(240),w,h,orientationBasis(0,180,0));
  assert.deepEqual([...panorama.pixels.slice(0,4)],[11,22,33,255]);
});
test('The dome consists of fixed hexagons and pentagons, including a zenith cell',()=>{
  assert.equal(DOME_CELLS.length,91);
  assert.ok(DOME_CELLS.every(c=>c.vertices.length===5||c.vertices.length===6));
  assert.ok(DOME_CELLS.some(c=>c.alt>89.99));
  for(const c of DOME_CELLS)for(const ray of [c.center,...c.vertices])near(Math.hypot(...ray),1);
});
test('A dot centred in the reticle captures its entire cell in portrait and landscape',()=>{
  for(const [width,height] of [[90,160],[160,90]]){
    const data=new Uint8ClampedArray(width*height*4).fill(200);
    for(const cell of DOME_CELLS){
      const panorama=new SkyPanorama(360,101),basis=lookBasis(cell.az,cell.alt);
      const at=projectRay(cell.center,basis,width,height)!;
      near(at.x,width/2);near(at.y,height/2);
      panorama.add(data,width,height,basis);
      assert.ok(panorama.covered(cell),`Centred cell ${cell.id} failed at ${width}x${height}`);
    }
  }
});
const separation=(a:V3,b:V3)=>Math.acos(Math.max(-1,Math.min(1,dot(a,b))))/DEG;
test('Every direction above the horizon has a target within the aim cone',()=>{
  // A one degree azimuth-altitude grid over everything the user can point at.
  // This is the SAMPLER: it drives `targetCell` end to end over the directions
  // a user can actually hold, and its worst aim (10.72) is below the true
  // bound, so a cone between the two would pass here. The case below is the
  // exact bound and the one that decides whether the cone is wide enough; this
  // one decides whether the lookup built on it works.
  const missed:string[]=[];let worst=0;
  for(let az=0;az<360;az++)for(let alt=0;alt<=90;alt++){
    const ray=skyVector(az,alt),cell=targetCell(ray);
    if(!cell){if(missed.length<8)missed.push(`az ${az} alt ${alt}`);continue;}
    const off=separation(ray,cell.center);
    worst=Math.max(worst,off);
    assert.ok(off<=AIM_CONE_DEG,`az ${az} alt ${alt} was given a target ${off.toFixed(2)} degrees away`);
  }
  assert.equal(missed.length,0,`directions with no target: ${missed.join(', ')}`);
  assert.ok(worst>10.5&&worst<AIM_CONE_DEG,`the worst aim in the grid was ${worst.toFixed(3)} degrees, so this grid no longer probes the cone's edge`);
  // Issue #57's own direction, which the old cones refused: exactly 5.00
  // degrees from the pole, against a 5 degree pole cone, and 12.17 from the
  // nearest cell of the first ring below it.
  const hold=skyVector(180,85),pole=DOME_CELLS.find(c=>c.alt>89.99)!;
  near(separation(hold,pole.center),5,.01);
  assert.equal(targetCell(hold)?.id,pole.id);
  // Mutation: AIM_CONE_DEG = 8 with the pole at 5, i.e. the cones this
  // replaced. 7713 of the 32760 grid directions (23.5 percent) lose their
  // target, the zenith hold among them. Observed red.
  // Below the horizon there is still nothing to aim at, which is what leaves
  // the 'Bring a blue dot into the centre ring' cue a job to do.
  for(const alt of [-12,-45,-90])assert.equal(targetCell(skyVector(0,alt)),null,`a target was offered at altitude ${alt}`);
});
test('The aim cone is wider than the farthest corner of any cell',()=>{
  // The closed form behind the grid above, and the reason 11 is the number.
  // The dome is a dual tiling: a cell's `vertices` ARE the points where three
  // cells meet, they are the farthest points of that cell from its own centre,
  // and no direction on the sphere is farther from the nearest centre than the
  // farthest such corner is from its own. So this single maximum is the exact
  // worst case a cone has to cover, with no grid spacing to sample past it.
  const separation=(a:V3,b:V3)=>Math.acos(Math.max(-1,Math.min(1,dot(a,b))))/DEG;
  let worst=0,worstCell=-1;
  for(const cell of DOME_CELLS)for(const corner of cell.vertices){
    const off=separation(cell.center,corner);
    if(off>worst){worst=off;worstCell=cell.id;}
  }
  // 10.8123 on this dome, attained at ten symmetric directions - azimuth 36,
  // 108, 180, 252 and 324 at altitude 52.62 AND at altitude 10.81.
  near(worst,10.81,.005);
  assert.ok(worst<AIM_CONE_DEG,
    `cell ${worstCell} reaches ${worst.toFixed(4)} degrees from its centre, outside the ${AIM_CONE_DEG} degree aim cone: `
    + 'directions inside that cell would have no target');
  // Mutation: AIM_CONE_DEG = 10. Red here (10.8123 is not below 10), and the
  // grid case above goes red with it. Observed red.
});
test('The target is the nearest cell, not the first in the list',()=>{
  // A direction inside two cells' cones at once, where DOME_CELLS order puts
  // the FARTHER of the two first. That is the case a first-match lookup gets
  // wrong, and the aim dot and the capture used to make this choice with two
  // different rules, so they could name two different patches.
  let probe:{ray:V3;nearer:DomeCell;farther:DomeCell}|null=null;
  for(let i=0;i<DOME_CELLS.length&&!probe;i++)for(let j=i+1;j<DOME_CELLS.length&&!probe;j++){
    const first=DOME_CELLS[i],second=DOME_CELLS[j];
    const ray=unit(first.center.map((v,k)=>v*.4+second.center[k]*.6) as V3);
    const a=separation(ray,first.center),b=separation(ray,second.center);
    if(a>=AIM_CONE_DEG||b>=a)continue;
    // The farther cell must also be the FIRST one in list order whose cone
    // contains the ray, or a first-match lookup would not have chosen it and
    // the mutation below would pass.
    if(DOME_CELLS.findIndex(c=>separation(ray,c.center)<AIM_CONE_DEG)===i)probe={ray,nearer:second,farther:first};
  }
  assert.ok(probe,'no direction lies in two cones with the farther cell earlier in the list');
  const {ray,nearer,farther}=probe!;
  assert.ok(separation(ray,nearer.center)<separation(ray,farther.center));
  assert.ok(separation(ray,farther.center)<AIM_CONE_DEG,'the farther cell is out of reach, so nothing is being chosen between');
  assert.equal(targetCell(ray)?.id,nearer.id,
    `the ray took cell ${targetCell(ray)?.id} at ${separation(ray,DOME_CELLS.find(c=>c.id===targetCell(ray)?.id)!.center).toFixed(2)} degrees `
    + `over cell ${nearer.id} at ${separation(ray,nearer.center).toFixed(2)}`);
  // Mutation: return the first cell within the cone instead of the nearest
  // (the DOME_CELLS.find this replaced). Red on the assertion above.
});
test('Earth-fixed references move with phone yaw, pitch and roll',()=>{
  const north=skyVector(0,0),base=orientationBasis(0,90,0);
  near(projectRay(north,base,400,300)!.x,200);near(projectRay(north,base,400,300)!.y,150);
  assert.ok(projectRay(north,orientationBasis(350,90,0),400,300)!.x<200);
  assert.ok(projectRay(north,orientationBasis(0,110,0),400,300)!.y>150);
  const up=skyVector(0,15);
  assert.ok(projectRay(up,base,400,300)!.y<150);
  assert.ok(projectRay(up,orientationBasis(0,90,0,90),400,300)!.x<200);
  assert.equal(projectRay(skyVector(180,0),base,400,300),null);
});
test('Zenith, compass wrap and landscape maintain a finite orthonormal camera frame',()=>{
  for(const basis of [orientationBasis(0,180,0),orientationBasis(359,90,0),orientationBasis(1,90,0),orientationBasis(270,0,90,270)]) {
    near(dot(basis.right,basis.forward),0);near(dot(basis.up,basis.forward),0);near(dot(basis.right,basis.up),0);
    const center=projectRay(basis.forward,basis,300,500)!;near(center.x,150);near(center.y,250);
  }
  const a=projectRay(skyVector(0,0),orientationBasis(359,90,0),400,300)!;
  const b=projectRay(skyVector(0,0),orientationBasis(1,90,0),400,300)!;
  assert.ok(Math.abs(a.x-b.x)<15);
});
function scene(basis:CameraBasis,width=160,height=120):Uint8ClampedArray {
  const data=new Uint8ClampedArray(width*height*4),lens=cameraLens(width,height);
  for(let y=0;y<height;y++)for(let x=0;x<width;x++){
    const sx=((x+.5)/width*2-1)*lens.tanX,sy=(1-(y+.5)/height*2)*lens.tanY;
    const ray=unit(basis.forward.map((v,i)=>v+basis.right[i]*sx+basis.up[i]*sy) as V3);
    const {az,alt}=skyAngles(ray),top=az>30&&az<90?75:az>180&&az<240?35:8;
    const color=alt<=top?[25,45,30,255]:[100,175,240,255];data.set(color,(y*width+x)*4);
  }
  return data;
}
const panorama=new SkyPanorama(720,201);
test('Overlapping colour frames form a full panorama with tall obstructions in place',()=>{
  for(const alt of [0,35,70,90])for(let az=0;az<360;az+=24){const basis=lookBasis(az,alt);panorama.add(scene(basis),160,120,basis);}
  assert.ok(DOME_CELLS.every(c=>panorama.covered(c)));
  const trace=traceSkyCoverage(panorama.columns(30));
  assert.deepEqual(trace.uncertainBins,[]);
  const house=trace.points.find(p=>p.az===54)!;near(house.alt,75,3);
  near(trace.points.find(p=>p.az===210)!.alt,35,3);
  near(trace.points.find(p=>p.az===138)!.alt,8,3);
  assert.ok(panorama.pixels.some((value,i)=>i%4===2&&value===240),'Blue sky RGB was discarded');
});
test('A partial panorama leaves unobserved pixels transparent and reports uncertain horizons',()=>{
  const partial=new SkyPanorama(360,101),basis=lookBasis(0,0);partial.add(scene(basis),160,120,basis);
  assert.equal(partial.has(skyVector(180,0)),false);
  assert.ok(traceSkyCoverage(partial.columns(30)).uncertainBins.length>0);
  assert.ok(DOME_CELLS.some(c=>!partial.covered(c)));
});
test('Capturing a cell centre alone does not turn the whole cell green',()=>{
  const empty=new SkyPanorama(360,101),cell=DOME_CELLS.find(c=>c.alt<45)!;
  const {az,alt}=skyAngles(cell.center),i=(Math.round(90-alt)*360+Math.floor(az))*4;
  empty.pixels.set([100,175,240,255],i);assert.equal(empty.has(cell.center),true);assert.equal(empty.covered(cell),false);
});
test('A truncated camera buffer cannot become a completed photograph',()=>{
  assert.throws(()=>panorama.add(new Uint8ClampedArray(4),160,120,lookBasis(0,0)),/incomplete/);
});
test('Overlap check catches inverted or misregistered textured frames without changing the panorama',()=>{
  const w=160,h=120,basis=lookBasis(0,25),data=scene(basis,w,h);
  const p=new SkyPanorama(720,201);p.add(data,w,h,basis);
  assert.equal(p.checkOverlap(data,w,h,basis).result,'agree');
  const exposure=data.map((v,i)=>i%4===3?v:Math.min(255,v*.65+12));
  assert.equal(p.checkOverlap(exposure,w,h,basis).result,'agree','Exposure alone is not misalignment');
  const inverted=new Uint8ClampedArray(data.length);
  for(let i=0;i<w*h;i++)inverted.set(data.subarray(i*4,i*4+4),(w*h-1-i)*4);
  const before=p.pixels.slice();
  assert.equal(p.checkOverlap(inverted,w,h,basis).result,'conflict');
  assert.deepEqual(p.pixels,before,'A rejected image changed the mosaic');
  const moved=lookBasis(12,30);
  assert.equal(p.checkOverlap(scene(moved,w,h),w,h,moved).result,'agree','Correctly projected overlap rejected');
});
test('No overlap and blank dark images cannot falsely certify image alignment',()=>{
  const p=new SkyPanorama(360,101),blank=new Uint8ClampedArray(160*120*4).fill(12),basis=lookBasis(0,20);
  assert.equal(p.checkOverlap(blank,160,120,basis).result,'unknown');
  p.add(blank,160,120,basis);
  assert.equal(p.checkOverlap(blank,160,120,basis).result,'unknown');
  assert.equal(p.checkOverlap(blank,160,120,lookBasis(180,20)).result,'unknown');
});
test('A per-camera view angle corrects measured landmark scale without a global lens change',()=>{
  // Anonymous pixel correspondences from a real portrait capture; no images or
  // site data. These are independent landmarks, not generated by our lens math.
  const a=[[4.5841,260.6341],[26.5302,180.0471],[39.9605,97.0203],[59.9944,216.0946],[63.5858,216.6722],[75.2438,185.0403]];
  const b=[[98.7680,304.0127],[122.3634,221.0654],[135.9827,138.6845],[156.6625,262.3046],[160.7399,263.4375],[173.1510,229.6636]];
  const rotation=[[.92379726,.01981706,.38236880],[.04116322,.98773119,-.15064094],[-.38066285,.15490123,.91164763]];
  const error=(fov:number)=>{
    const lens=cameraLens(180,320,fov);
    return Math.sqrt(a.reduce((sum,p,i)=>{
      const ray=[(p[0]/180*2-1)*lens.tanX,(1-p[1]/320*2)*lens.tanY,1];
      const out=rotation.map(row=>row.reduce((n,v,j)=>n+v*ray[j],0));
      const x=90+90*out[0]/(out[2]*lens.tanX),y=160-160*out[1]/(out[2]*lens.tanY);
      return sum+(x-b[i][0])**2+(y-b[i][1])**2;
    },0)/a.length);
  };
  assert.ok(error(60)>30);assert.ok(error(41.1)<4);
  near(cameraLens(180,320).tanX,Math.tan(Math.PI/6));
  near(cameraLens(320,180,41.1).tanY,cameraLens(180,320,41.1).tanX);
  // Overlay and saved image receive the same calibrated lens.
  const lens=cameraLens(180,320,41.1),mark=projectRay(skyVector(15,0),lookBasis(0,0),180,320,lens)!;
  near(mark.x,90+90*Math.tan(15*DEG)/Math.tan(41.1/2*DEG));
});
console.log(`photosphereGeometry.test: ${passed}/${passed} passed`);
export const result={passed,failed:0,total:passed};
