// altaz.ts — RA/Dec to horizon coordinates, for putting a plan's targets on
// the sky dome.
//
// A PORT, NOT AN INVENTION. This is line-for-line the server's
// `catalog/coords.py` `lst_hours` + `altaz`, and the test pins it against
// values generated by running that Python. Two implementations of spherical
// astronomy in one product is how a target ends up drawn in the wrong half of
// the sky while every unit test passes, so when these disagree the PYTHON is
// right and this is the bug.
//
// WHY CLIENT-SIDE AT ALL. The dome redraws on a 2 s status frame and a target
// mark has to move with it; a round trip per target per frame is a request
// storm for a decoration. The tolerance is generous in the other direction
// too: one dome cell is 6 x 10 degrees, so an error that would matter here is
// an error nobody could make accidentally.
//
// NOT FOR POINTING. Good to about a second of sidereal time, which is fine for
// "which way is that object" and nowhere near good enough to slew on. Nothing
// here feeds a mount command, and nothing here should.

/** Local sidereal time in hours, [0, 24). */
export function lstHours(longitudeDeg: number, unixTime: number): number {
  const jd = unixTime / 86400.0 + 2440587.5;
  const d = jd - 2451545.0;
  const gmst = mod(18.697374558 + 24.06570982441908 * d, 24.0);
  return mod(gmst + longitudeDeg / 15.0, 24.0);
}

/** Positive modulo: JS `%` keeps the sign of the dividend, Python's does not. */
function mod(x: number, m: number): number {
  return ((x % m) + m) % m;
}

export interface AltAz {
  /** Degrees above the horizon. NEGATIVE means below it -- the caller decides
   *  whether that is "do not draw" or "draw it greyed"; this does not clamp,
   *  because clamping would put a target that has set on the horizon as though
   *  it were still up. */
  altDeg: number;
  /** Degrees east of north, [0, 360). */
  azDeg: number;
}

const DEG = Math.PI / 180;

/** Where an equatorial coordinate is in the sky, from a site, at an instant. */
export function altAzOf(raHours: number, decDeg: number, latDeg: number,
                        lonDeg: number, unixTime: number): AltAz {
  const lst = lstHours(lonDeg, unixTime);
  const ha = (lst - raHours) * 15.0 * DEG;
  const dec = decDeg * DEG;
  const lat = latDeg * DEG;

  const sinAlt = Math.sin(dec) * Math.sin(lat)
    + Math.cos(dec) * Math.cos(lat) * Math.cos(ha);
  const alt = Math.asin(Math.max(-1, Math.min(1, sinAlt)));

  // The 1e-9 floor is the server's, kept: at the pole cos(alt)cos(lat) goes to
  // zero and the quotient is 0/0. Dropping it gives NaN for an observer at the
  // pole and for a target exactly overhead -- both of which are drawable.
  const cosAz = (Math.sin(dec) - Math.sin(alt) * Math.sin(lat))
    / Math.max(1e-9, Math.cos(alt) * Math.cos(lat));
  let az = Math.acos(Math.max(-1, Math.min(1, cosAz)));
  if (Math.sin(ha) > 0) az = 2 * Math.PI - az;

  return { altDeg: alt / DEG, azDeg: mod(az / DEG, 360.0) };
}
