// credits.ts — shape and search for the third-party credits screen.
//
// The DATA is generated by `python tools/gen_credits.py` into
// `src/credits.generated.json`, straight out of the real manifests (the
// installed Python environment, package-lock.json, Cargo.lock, the vendor
// directory, the catalogue data directory). Nothing here is written by hand,
// and `server/tests/test_credits.py` fails the build when a dependency exists
// with no entry.
//
// This module holds only what a test can exercise without a DOM: the types, the
// plain-English rendering of an obligation code, and the filter. The panel that
// draws them is components/settings/CreditsPanel.tsx.

export type ObligationCode =
  | "notice"
  | "license"
  | "notice-file"
  | "state-changes"
  | "source"
  | "attribution"
  | "share-alike"
  | "no-sell-alone"
  | "reserved-name";

export interface CreditText {
  title: string;
  hash: string;
}

export interface CreditEntry {
  name: string;
  version: string;
  spdx: string;
  tier: string;
  requires: string[];
  summaries: string[];
  texts: CreditText[];
  url?: string;
  notes?: string;
  /** Set when the licence needs an owner decision rather than a credit line. */
  flag?: string;
}

export interface CreditGroup {
  id: string;
  title: string;
  blurb: string;
  entries: CreditEntry[];
}

export interface CreditsDoc {
  generator: string;
  project: { name: string; version: string; spdx: string };
  scope: string;
  /** Licence bodies, de-duplicated by content hash and referenced by entries. */
  licenses: Record<string, string>;
  groups: CreditGroup[];
}

/** Short label for an obligation, for the chips under an entry's name.
 *
 *  These are the *obligations*, not the licence name. "MIT" tells a reader
 *  nothing about what we had to do; "notice reproduced" does. Anything not in
 *  this map is shown verbatim rather than silently dropped — an unknown
 *  obligation is exactly the thing that must not disappear from a compliance
 *  screen. */
const OBLIGATION_LABEL: Record<string, string> = {
  "notice": "notice reproduced",
  "license": "full licence text",
  "notice-file": "NOTICE carried forward",
  "state-changes": "changes stated",
  "source": "source for modified files",
  "attribution": "attribution",
  "share-alike": "share-alike",
  "no-sell-alone": "not sold on its own",
  "reserved-name": "reserved font name",
};

export function obligationLabel(code: string): string {
  return OBLIGATION_LABEL[code] ?? code;
}

/** Total entries across every group. */
export function countEntries(doc: CreditsDoc): number {
  return doc.groups.reduce((n, g) => n + g.entries.length, 0);
}

/** Entries whose licence still needs a decision from the project owner. */
export function flaggedEntries(doc: CreditsDoc): CreditEntry[] {
  return doc.groups.flatMap((g) => g.entries.filter((e) => !!e.flag));
}

/** Does this entry reproduce a real licence body, or only name one?
 *
 *  Naming a licence is not compliance, so the screen distinguishes the two and
 *  the test suite asserts that nothing requiring text is missing it. A hash
 *  that resolves to nothing counts as missing, not as present-but-empty. */
export function hasReproducedText(doc: CreditsDoc, entry: CreditEntry): boolean {
  return entry.texts.some((t) => (doc.licenses[t.hash] ?? "").trim().length > 0);
}

/** Case-insensitive search over the fields a person would actually search by.
 *
 *  Licence BODIES are deliberately excluded from the haystack: every MIT
 *  package contains the word "warranty", so including the text would make most
 *  queries match almost everything and the filter would be useless. Name,
 *  version, licence id and our own notes are what distinguish one entry from
 *  another. */
export function entryMatches(entry: CreditEntry, query: string): boolean {
  const q = query.trim().toLowerCase();
  if (!q) return true;
  const hay = [
    entry.name,
    entry.version,
    entry.spdx,
    entry.notes ?? "",
    entry.flag ?? "",
    entry.url ?? "",
    ...entry.requires.map(obligationLabel),
  ]
    .join(" ")
    .toLowerCase();
  // Every whitespace-separated term must appear, so "zwo mit" narrows rather
  // than widens.
  return q.split(/\s+/).every((term) => hay.includes(term));
}

/** Groups with their entries filtered, dropping groups left with nothing.
 *
 *  Returning an empty group would render a heading over blank space, which
 *  reads as "there is nothing here" rather than "nothing here matched". */
export function filterGroups(doc: CreditsDoc, query: string): CreditGroup[] {
  return doc.groups
    .map((g) => ({ ...g, entries: g.entries.filter((e) => entryMatches(e, query)) }))
    .filter((g) => g.entries.length > 0);
}
