import {JSDOM} from "jsdom";
const dom=new JSDOM('<div id="root"></div>',{url:'http://local/',pretendToBeVisual:true});
const win=dom.window as any;
win.HTMLCanvasElement.prototype.getContext=()=>null;
for(const k of ['window','document','navigator','HTMLElement','Event','MouseEvent'])Object.defineProperty(globalThis,k,{value:k==='window'?win:win[k],configurable:true});
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
const {createElement:h,act}=await import('react'); const {createRoot}=await import('react-dom/client'); const {AlignmentCoach}=await import('../AlignmentCoach');
const root=createRoot(win.document.getElementById('root'));
const render=async(props:any)=>act(async()=>root.render(h(AlignmentCoach,{total:45,az:40,alt:5,south:false,running:true,blocked:false,...props})));
let passed=0,failed=0;const test=(name:string,fn:()=>void)=>{try{fn();passed++;}catch(e){failed++;console.log(name,e);}};const assert=(v:unknown)=>{if(!v)throw new Error('assertion failed');};
await render({});
test('large errors show whole-rig movement and stop/restart instructions',()=>{assert(win.document.querySelector('canvas').getAttribute('aria-label').includes('all three tripod legs rotate together'));assert(win.document.body.textContent.includes('Stop alignment'));assert(win.document.body.textContent.includes('Start a new alignment'));});
await render({total:20,az:19});
test('nearer alignment shows fixed tripod and azimuth adjusters',()=>{assert(win.document.querySelector('canvas').getAttribute('aria-label').includes('tripod feet stay fixed'));assert(win.document.body.textContent.includes('Turn the mount sideways'));});
await act(async()=>[...win.document.querySelectorAll('button')].find((b:any)=>b.textContent==='Tilt · altitude').click());
test('altitude has its own selectable explanation',()=>assert(win.document.body.textContent.includes('Tilt the mount up or down')));
await render({total:20,blocked:true});
test('stale or suspect measurements suppress instructions to adjust',()=>assert(win.document.body.textContent.includes('Wait for a reliable measurement')));
await act(async()=>[...win.document.querySelectorAll('button')].find((b:any)=>b.textContent==='Pause example').click());
test('the animation has a reachable pause control',()=>assert(win.document.body.textContent.includes('Play example')));
await act(async()=>root.unmount());console.log(`alignment coach: ${passed}/${passed+failed} passed`);export const result={passed,failed,total:passed+failed};if(failed)process.exitCode=1;
