import {JSDOM} from "jsdom";
const dom=new JSDOM('<div id="root"></div>',{url:"http://local/",pretendToBeVisual:true});
const win=dom.window as any;
for(const key of ["window","document","navigator","HTMLElement","Event","MouseEvent","localStorage"])Object.defineProperty(globalThis,key,{value:key==="window"?win:win[key],configurable:true});
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
let stops=0;
let onStop:()=>void=()=>{};
Object.assign(globalThis,{fetch:async(url:string)=>{if(url==="/api/polar/stop"){stops++;onStop();}return{ok:true,status:200,json:async()=>({stopped:true})};}});
const {createElement:h,act}=await import("react");const {createRoot}=await import("react-dom/client");
const {useStore}=await import("../../store");const {useGuidedSetup}=await import("../setup");const {AlignmentFinish}=await import("../AlignmentFinish");
onStop=()=>useStore.setState({polar:{...useStore.getState().polar,state:"idle"}} as never);
const stamp=Date.now()/1000;
const base={state:"running",phase:"adjusting",total_error:1.5,reading_ts:stamp,flags:[],stale_updates:0};
useStore.setState({wsPhase:"up",telemetryStale:false,status:{mount:{slewing:false},connected:{telescope:{connected:true}}},principal:{role:"admin",caps:["control.mount"]},polar:base} as never);
const root=createRoot(win.document.getElementById("root"));await act(async()=>root.render(h(AlignmentFinish)));
const finish=()=>win.document.querySelector("button") as HTMLButtonElement;
let passed=0,failed=0;function test(n:string,f:()=>void){try{f();passed++;}catch(e){failed++;console.log(n,e);}}function assert(v:unknown){if(!v)throw new Error("assertion failed");}
await act(async()=>useStore.setState({polar:{...base,state:"idle",total_error:0,reading_ts:0}} as never));
test("idle alignment does not offer a final check",()=>assert(!win.document.querySelector("input")));
await act(async()=>useStore.setState({polar:{...base,phase:"measuring"}} as never));
test("initial measurement does not offer a final check",()=>assert(!win.document.querySelector("input")));
await act(async()=>useStore.setState({polar:{...base,total_error:35}} as never));
test("rough alignment does not offer a final check",()=>assert(!win.document.querySelector("input")));
await act(async()=>useStore.setState({polar:base} as never));
test("a small error alone cannot finish alignment",()=>assert(finish().disabled));
await act(async()=>win.document.querySelector("input").click());
test("locking requires a subsequent measurement",()=>assert(finish().disabled));
await act(async()=>useStore.setState({polar:{...base,reading_ts:stamp+1,stale_updates:1}} as never));
test("stale solves cannot certify completion",()=>assert(finish().disabled));
await act(async()=>useStore.setState({polar:{...base,reading_ts:stamp+2,flags:["initial_error_large"]}} as never));
test("large-error model warnings prevent completion",()=>assert(finish().disabled));
await act(async()=>useStore.setState({polar:{...base,reading_ts:stamp+3}} as never));
test("fresh good post-lock measurement enables completion",()=>assert(!finish().disabled));
await act(async()=>finish().click());
test("finishing stops the session before certifying alignment",()=>{assert(stops===1);assert(useGuidedSetup.getState().alignment);assert(win.document.body.textContent.includes("Alignment checked"));});
await act(async()=>{useGuidedSetup.setState({alignment:false});useStore.setState({polar:{...base,state:"idle"}} as never);});
await act(async()=>useStore.setState({polar:{...base,state:"done",total_error:0,reading_ts:stamp+4}} as never));
test("a terminal zero-error measurement offers a final confirmation",()=>assert(win.document.querySelector("input")&&finish().disabled));
await act(async()=>win.document.querySelector("input").click());
test("confirming secure locks at the measured terminal frame enables finish",()=>assert(!finish().disabled));
await act(async()=>finish().click());
test("terminal success unlocks the next Guided step",()=>assert(useGuidedSetup.getState().alignment&&stops===2));
await act(async()=>{useGuidedSetup.setState({alignment:false});useStore.setState({polar:{...base,state:"done",total_error:22}} as never);});
test("an ended session above the target cannot certify alignment",()=>assert(!win.document.querySelector("input")));
await act(async()=>useStore.setState({polar:{...base,state:"done",reading_ts:stamp-600}} as never));
test("an old terminal measurement cannot certify alignment",()=>assert(finish().disabled&&win.document.body.textContent.includes("too old")));
await act(async()=>useStore.setState({polar:{...base,state:"idle"}} as never));
await act(async()=>useStore.setState({polar:{...base,state:"done",reading_ts:Date.now()/1000}} as never));
await act(async()=>win.document.querySelector("input").click());
onStop=()=>useStore.setState({polar:{...useStore.getState().polar,state:"idle",reading_ts:Date.now()/1000+.1}} as never);
await act(async()=>finish().click());
test("a newer good solve during stop still completes alignment",()=>assert(useGuidedSetup.getState().alignment&&stops===3));
await act(async()=>{useGuidedSetup.setState({alignment:false});useStore.setState({polar:{...base,state:"done",reading_ts:Date.now()/1000}} as never);});
await act(async()=>win.document.querySelector("input").click());
onStop=()=>useStore.setState({polar:{...useStore.getState().polar,state:"idle",total_error:NaN}} as never);
await act(async()=>finish().click());
test("invalid final telemetry cannot certify and leaves a recovery message",()=>assert(!useGuidedSetup.getState().alignment&&win.document.querySelector('[role="alert"]')&&win.document.body.textContent.includes("Start a new alignment")));
await act(async()=>root.unmount());console.log(`guided alignment: ${passed}/${passed+failed} passed`);export const result={passed,failed,total:passed+failed};if(failed)process.exitCode=1;
