import {JSDOM} from "jsdom";
const dom=new JSDOM('<div id="root"></div>',{url:"http://local/",pretendToBeVisual:true});
const win=dom.window as any;
win.matchMedia=()=>({matches:true,addEventListener(){},removeEventListener(){}});
for(const key of ["window","document","navigator","HTMLElement","Element","Node","Event","MouseEvent","KeyboardEvent","localStorage","requestAnimationFrame","cancelAnimationFrame","getComputedStyle"])Object.defineProperty(globalThis,key,{value:key==="window"?win:win[key],configurable:true});
Object.assign(globalThis,{IS_REACT_ACT_ENVIRONMENT:true});
const {createElement:h,act}=await import("react");const {createRoot}=await import("react-dom/client");
const {FocusTutorial}=await import("../FocusTutorial");const {GuidedScrollCue}=await import("../GuidedScrollCue");const {useExperience}=await import("../experience");
useExperience.setState({wizard:"focus"});
let opened=0;const root=createRoot(win.document.getElementById("root"));
await act(async()=>root.render(h("div",null,h("main",{id:"main-content"},h(FocusTutorial,{disabled:false,onDefaults:()=>{},onComplete:()=>opened++})),h("footer",null,h("div",{id:"guided-lesson-actions"}),h(GuidedScrollCue)))));
const pane=win.document.getElementById("main-content");
Object.defineProperty(pane,"clientHeight",{value:500});Object.defineProperty(pane,"scrollHeight",{value:1000});
let scrollRequest:any;pane.scrollBy=(options:any)=>{scrollRequest=options;};
let passed=0,failed=0;function test(name:string,fn:()=>void){try{fn();passed++;}catch(e){failed++;console.log(name,e);}}function assert(value:unknown){if(!value)throw new Error("assertion failed");}
test("lesson navigation lives outside the scrolling content",()=>{assert(win.document.querySelector("footer").textContent.includes("Next tip"));assert(!pane.textContent.includes("Next tip"));});
await act(async()=>[...win.document.querySelectorAll("button")].find((b:any)=>b.textContent==="Next tip").click());
test("fixed lesson navigation still changes the current explanation",()=>assert(pane.textContent.includes("Start with a short exposure")));
await act(async()=>[...win.document.querySelectorAll("button")].find((b:any)=>b.textContent.includes("Open camera view")).click());
test("opening the camera is an explicit action",()=>assert(opened===1));
const click=async(selector:string)=>{await act(async()=>win.document.querySelector(selector).click());};
const sky=()=>pane.querySelector('.guided-practice-stars');
const initialBrightness=sky().querySelector('g').getAttribute('opacity');
await click('button[aria-label^="Practice camera settings"]');
await click('[data-dial-item="exposure"]');
const exposureOption=[...win.document.querySelectorAll('button')].find((b:any)=>b.textContent==='5s');
await act(async()=>exposureOption.click());
test("practice exposure changes the star image and explains why",()=>assert(sky().getAttribute('aria-label').includes('5s')&&sky().querySelector('g').getAttribute('opacity')!==initialBrightness&&pane.textContent.includes('gathers light')));
await click('button[aria-label^="Practice camera settings"]');
await click('[data-dial-item="binning"]');
await click('[data-dial-item="2"]');
test("practice binning changes image sampling and explains 1x1",()=>assert(sky().getAttribute('viewBox')==='0 0 270 170'&&pane.textContent.includes('half as many pixels')));
await act(async()=>pane.dispatchEvent(new win.Event("scroll")));
const cue=()=>[...win.document.querySelectorAll("button")].find((b:any)=>b.textContent.includes("More below"));
test("overflow gets a visible navigation cue",()=>assert(cue()));
await act(async()=>cue().click());
test("cue scrolls the working pane and respects reduced motion",()=>assert(scrollRequest.top===350&&scrollRequest.behavior==="auto"));
await act(async()=>{pane.scrollTop=500;pane.dispatchEvent(new win.Event("scroll"));});
test("cue disappears once the bottom is reached",()=>assert(!cue()));
await act(async()=>root.unmount());console.log(`guided lesson navigation: ${passed}/${passed+failed} passed`);export const result={passed,failed,total:passed+failed};if(failed)process.exitCode=1;
