"""``POST /api/flows/quick`` and ``flows.wizard.quick`` -- the one-screen night.

The quick sheet exists because the guided wizard still asks an operator to
answer "what kind of night" and then hands them a canvas. The common case does
not need a canvas: a target, a number of subs, the filters, go. What makes that
safe to ship is that it is not a NEW night -- it is the shape the rig has
already shot, generated by the same ``generate()`` the wizard uses.

So the four things this file pins are the four ways that promise could be
broken while every other test stayed green:

1. **The graph runs.** Not "compiles": ``to_plan`` is where a graph stops being
   a picture, and a FILTER CYCLE with an empty slot table or a zero-second slot
   is refused there and nowhere earlier. The plan's own step list is checked
   against the slot table, because a cycle that compiled to the wrong counts
   would still be a plan.

2. **The doctor is silent.** wizard.py's header calls this the acceptance bar
   and says why: a generated graph that arrives already lit up with warnings
   teaches a first-time operator, on their first flow, that the doctor is
   decoration.

3. **A filter this wheel does not have is refused, 422.** cyclePlanRows.ts
   opens on the reason -- a filter name is not a label; it lands in the FITS
   ``FILTER`` header, in the filename and in the calibration matcher's key.
   Accepting ``OIII`` on a wheel whose slot reads ``Oiii`` produces a night that
   asks for a filter that does not exist, and finds out at 21:00.

4. **The run is the SAME handler.** ``/api/flows/{id}/run`` applies five guards
   in a fixed order and its docstring says a second start path that quietly
   omits one is how a guard stops being a guard. This route must not be that
   second path -- so the tests below drive guards that live ONLY inside that
   handler and require them to fire through this route.
"""
from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

import astrodeck.api.app as app_module
from astrodeck.config import ConfigStore
from astrodeck.flows import wizard
from astrodeck.flows.compile import compile_plan
from astrodeck.flows.doctor import check as flow_doctor
from astrodeck.flows.models import MY_FLOWS_FOLDER
from astrodeck.flows.nodes import parse_cycle_plan
from astrodeck.flows.store import FlowStore
from astrodeck.flows.to_plan import to_sequence_plan

#: A real catalogue row, in the strings the TARGET node stores.
NGC6946 = {"name": "NGC 6946", "ra": "20h 34m 52s", "dec": "+60 09 14"}


@pytest.fixture
def client(tmp_path, monkeypatch):
    temp_store = ConfigStore(path=tmp_path / "astrodeck.json")
    import astrodeck.config as config_mod
    import astrodeck.hub as hub_mod
    monkeypatch.setattr(config_mod, "config_store", temp_store)
    monkeypatch.setattr(hub_mod, "config_store", temp_store)
    monkeypatch.setattr(app_module, "config_store", temp_store)
    monkeypatch.setattr(config_mod, "CONFIG_DIR", tmp_path)
    monkeypatch.setattr(app_module, "flow_store", FlowStore(tmp_path / "flows"))
    with TestClient(app_module.create_app()) as c:
        yield c


def _post(c, **body):
    body.setdefault("target", NGC6946)
    return c.post("/api/flows/quick", json=body)


def _node(record, node_type):
    return next(n for n in record.graph.nodes if n.type == node_type)


# ----------------------------------------------------------- the generator
class TestTheGeneratedGraph:
    def test_the_cycle_carries_the_ticked_filters_in_wheel_order(self):
        """Wheel order, not click order.

        The cycle shoots its table top to bottom on every pass, so a table in
        the order the checkboxes happened to be clicked makes the carousel take
        the long way round most passes -- and makes two operators who ticked the
        same five filters get two different nights.
        """
        rec = wizard.quick(NGC6946, 12, ["Ha", "B", "L", "G", "R"])
        assert _node(rec, "cycle").params["plan"] == "L 60, R 60, G 60, B 60, Ha 180"

    def test_subs_per_filter_is_the_cycle_count_at_one_per_pass(self):
        """``cycles`` x ``perCycle`` is what each filter owes. perCycle must
        stay 1, or "12 subs each" silently becomes 24."""
        cyc = _node(wizard.quick(NGC6946, 12, ["L", "R"]), "cycle").params
        assert (cyc["cycles"], cyc["perCycle"]) == (12, 1)

    def test_narrowband_defaults_to_180s_and_broadband_to_60(self):
        """60 s of Ha is an empty frame. The spellings vary by wheel, which is
        why the match is by prefix and by the SHO single letters."""
        plan = _node(wizard.quick(NGC6946, 1, ["L", "Ha", "Oiii", "S"],
                                  wheel=["L", "Ha", "Oiii", "S"]),
                     "cycle").params["plan"]
        assert plan == "L 60, Ha 180, Oiii 180, S 180"

    def test_a_given_exposure_beats_the_default(self):
        plan = _node(wizard.quick(NGC6946, 1, ["L", "Ha"], {"L": 30, "Ha": 300}),
                     "cycle").params["plan"]
        assert plan == "L 30, Ha 300"

    def test_the_target_carries_its_coordinates_not_just_its_name(self):
        """A TARGET whose name was replaced and whose ra/dec were not slews to
        the node's shipped M31 and files the frames under the name typed --
        ``to_plan`` reads ra/dec and never the name."""
        t = _node(wizard.quick(NGC6946, 4, ["L"]), "target").params
        assert (t["name"], t["ra"], t["dec"]) == ("NGC 6946", NGC6946["ra"],
                                                  NGC6946["dec"])

    def test_it_is_the_proven_deep_sky_shape(self):
        """Dusk window, target, slew + center, autofocus, guide, the capture
        stage, session report -- plus the relative HFR watchdog and a safety
        monitor that aborts and parks."""
        rec = wizard.quick(NGC6946, 10, ["L"])
        types = [n.type for n in rec.graph.nodes]
        for want in ("dusk", "target", "slew", "autofocus", "guide", "cycle",
                     "report", "condition", "refocus", "safety", "abort"):
            assert want in types, f"a quick flow with no {want}: {types}"
        cond = _node(rec, "condition").params
        assert cond["when"] == "HFR above (x focus)" and cond["threshold"] == 1.3

    def test_the_watchdog_is_fed_by_the_cycle_and_fires_the_refocus(self):
        """A CONDITION with nothing wired into `events` never fires, and one
        that fires into nothing does nothing. Either is a rule that looks
        present on the canvas and is inert."""
        rec = wizard.quick(NGC6946, 10, ["L"])
        cyc, cond, refo = (_node(rec, t) for t in ("cycle", "condition", "refocus"))
        edges = {(e.from_, e.fromPort, e.to, e.toPort) for e in rec.graph.edges}
        assert (cyc.id, "frame", cond.id, "events") in edges
        assert (cond.id, "fire", refo.id, "do") in edges

    def test_the_safety_monitor_actually_aborts(self):
        """SAFETY MONITOR has no inputs, so the doctor cannot see one whose
        `unsafe` event goes nowhere. A bare monitor closes nothing on rain."""
        rec = wizard.quick(NGC6946, 10, ["L"])
        safety, abort = _node(rec, "safety"), _node(rec, "abort")
        assert any(e.from_ == safety.id and e.fromPort == "unsafe"
                   and e.to == abort.id for e in rec.graph.edges)

    def test_unguided_drops_the_guide_node_and_keeps_the_rest(self):
        rec = wizard.quick(NGC6946, 10, ["L"], guided=False)
        types = [n.type for n in rec.graph.nodes]
        assert "guide" not in types and "cycle" in types and "abort" in types

    def test_no_wheel_is_one_channel_with_no_filter_name(self):
        """A colour camera has one channel. A one-slot FILTER CYCLE interleaves
        nothing and would have to invent a slot name -- and an invented filter
        name is what lands in the FITS header and the calibration key."""
        rec = wizard.quick(NGC6946, 30, [], {"OSC": 90})
        assert not any(n.type == "cycle" for n in rec.graph.nodes)
        cap = _node(rec, "capture").params
        assert (cap["filter"], cap["exposure"], cap["count"]) == ("", 90, 30)
        assert cap["goal"] == 0, (
            "the cycle path carries no integration target, so the one-channel "
            "path must not silently keep the node's shipped 12-hour goal")

    def test_it_lands_in_my_flows_and_says_what_it_is(self):
        rec = wizard.quick(NGC6946, 12, ["L", "R", "G", "B", "Ha"])
        assert rec.folder == MY_FLOWS_FOLDER and rec.readonly is False
        assert "12 subs" in rec.tagline and "NGC 6946" in rec.tagline
        assert "60 frames" in rec.tagline, (
            f"the card's only line of prose does not say how big the night is: "
            f"{rec.tagline!r}")

    @pytest.mark.parametrize("bad, why", [
        ({"name": "NGC 6946"}, "no coordinates"),
        ({"name": "NGC 6946", "ra": "not a time", "dec": "+60 09 14"}, "bad RA"),
        ({"name": "", "ra": "20h", "dec": "+60"}, "no name"),
    ])
    def test_a_target_the_run_could_not_use_is_refused_at_the_door(self, bad, why):
        with pytest.raises(ValueError):
            wizard.quick(bad, 10, ["L"])

    def test_zero_subs_is_refused(self):
        """A flow with no frames reports "complete" having shot none."""
        with pytest.raises(ValueError):
            wizard.quick(NGC6946, 0, ["L"])

    def test_a_filter_the_wheel_does_not_have_is_refused(self):
        with pytest.raises(ValueError) as e:
            wizard.quick(NGC6946, 10, ["OIII"], wheel=["L", "R", "G", "B", "Oiii"])
        assert "OIII" in str(e.value) and "Oiii" in str(e.value)

    def test_the_assumed_wheel_is_the_cycle_nodes_own_default_plan(self):
        """One list of assumed filters on the server. A second copy is how the
        editor's fresh cycle node and a quick flow come to disagree about what a
        rig with no wheel is presumed to have."""
        from astrodeck.flows.nodes import NODE_DEFS
        assert wizard.fallback_wheel() == [
            f for f, _ in parse_cycle_plan(NODE_DEFS["cycle"].params["plan"])]


class TestItPassesItsOwnDoctorAndRuns:
    def test_a_guided_quick_flow_has_no_issues_at_all(self):
        """The stated acceptance bar. Not "nothing above warn" -- nothing."""
        rec = wizard.quick(NGC6946, 12, ["L", "R", "G", "B", "Ha"])
        issues = [(i.level, i.text) for i in flow_doctor(rec.graph)]
        assert issues == [], issues

    @pytest.mark.parametrize("filters", [["L"], ["L", "R", "G", "B"],
                                         ["Ha", "OIII", "SII"], []])
    def test_every_filter_subset_is_clean(self, filters):
        rec = wizard.quick(NGC6946, 8, filters)
        assert [i.text for i in flow_doctor(rec.graph) if i.level != "note"] == []

    def test_it_reaches_a_runnable_plan_with_the_frames_asked_for(self):
        """``to_plan`` is where a graph stops being a picture. A cycle with an
        empty table or a zero-second slot is refused HERE and nowhere earlier.
        """
        rec = wizard.quick(NGC6946, 12, ["L", "R", "G", "B", "Ha"])
        plan, _unmapped = to_sequence_plan(compile_plan(rec.graph, rec.name),
                                           rec.graph)
        assert plan.total_frames() == 60, "12 subs x 5 filters is 60 frames"
        target = plan.targets[0]
        assert target.acquisition == "cycle", (
            "without acquisition=cycle the engine walks the steps block by "
            "block: 12 L, then 12 R -- a mono image at every prefix, which is "
            "the arrangement the cycle node exists to avoid")
        assert [(s.filter, s.exposure_s, s.count) for s in target.steps] == [
            ("L", 60, 12), ("R", 60, 12), ("G", 60, 12), ("B", 60, 12),
            ("Ha", 180, 12)]

    def test_the_one_channel_flow_runs_too(self):
        rec = wizard.quick(NGC6946, 30, [], {"OSC": 90})
        plan, _ = to_sequence_plan(compile_plan(rec.graph, rec.name), rec.graph)
        assert plan.total_frames() == 30


# ----------------------------------------------------------------- the route
class TestTheRoute:
    def test_it_saves_a_flow_the_library_can_open(self, client):
        r = _post(client, subs=12, filters=["L", "R", "G", "B", "Ha"])
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["started"] is False
        fid = body["flow"]["id"]
        got = client.get(f"/api/flows/{fid}")
        assert got.status_code == 200, "generated but not saved"
        cyc = next(n for n in got.json()["graph"]["nodes"] if n["type"] == "cycle")
        assert cyc["params"]["plan"] == "L 60, R 60, G 60, B 60, Ha 180"
        assert cyc["params"]["cycles"] == 12

    def test_it_is_editable_from_the_moment_it_appears(self, client):
        body = _post(client, subs=5, filters=["L"]).json()["flow"]
        assert body["folder"] == MY_FLOWS_FOLDER and body["readonly"] is False

    def test_the_saved_graph_passes_the_doctor_through_the_route(self, client):
        """Checked on what the ROUTE returns, after serialisation and
        persistence -- which is the graph a first-time operator sees light up,
        or not."""
        fid = _post(client, subs=9, filters=["L", "Ha"]).json()["flow"]["id"]
        out = client.post(f"/api/flows/{fid}/compile").json()
        assert out["structural"] == []
        assert [i for i in out["issues"] if i["level"] != "note"] == [], out["issues"]

    def test_an_unknown_filter_is_a_422_naming_it(self, client):
        r = _post(client, subs=10, filters=["Purple"])
        assert r.status_code == 422, r.text
        assert "Purple" in str(r.json()["detail"])

    def test_a_target_with_no_coordinates_is_a_422(self, client):
        r = client.post("/api/flows/quick",
                        json={"target": {"name": "NGC 6946"}, "filters": ["L"]})
        assert r.status_code == 422, r.text

    def test_the_wheel_it_validates_against_is_the_CONNECTED_one(self, client,
                                                                 monkeypatch):
        """A rig with a wheel gets that wheel, blackout slots removed. An opaque
        slot passes no light, so a Light frame through it is a black frame with
        IMAGETYP=Light on it."""
        class _Wheel:
            connected = True
            filter_names = ["L", "Dark", "Oiii"]

            def is_opaque(self, i):
                return i == 1

        monkeypatch.setitem(app_module.hub.devices, "filterwheel", _Wheel())
        assert _post(client, filters=["Dark"]).status_code == 422, (
            "a blackout slot was offered as a light-frame filter")
        assert _post(client, filters=["OIII"]).status_code == 422, (
            "the connected wheel spells it Oiii; OIII is a filter it does not "
            "have")
        ok = _post(client, subs=3, filters=["Oiii", "L"])
        assert ok.status_code == 200, ok.text
        cyc = next(n for n in ok.json()["flow"]["graph"]["nodes"]
                   if n["type"] == "cycle")
        assert cyc["params"]["plan"] == "L 60, Oiii 180"

    def test_it_declares_the_motion_sink_it_reaches(self):
        """``reaches={"SequenceEngine.start"}`` is what ARMS the boot check that
        a mount-motion route is gated on control.mount. Omitting it boots clean
        while shipping a motion route behind control.capture."""
        from astrodeck.auth.capabilities import (CAP_CONTROL_CAPTURE,
                                                 CAP_CONTROL_MOUNT)
        from astrodeck.auth.rbac import CAP_ATTR, REACHES_ATTR
        app = app_module.create_app()
        route = next(r for r in app.routes
                     if getattr(r, "path", "") == "/api/flows/quick")
        assert "SequenceEngine.start" in getattr(route.endpoint, REACHES_ATTR, set())
        caps = getattr(route.endpoint, CAP_ATTR, set())
        assert {CAP_CONTROL_MOUNT, CAP_CONTROL_CAPTURE} <= caps

    def test_it_is_matched_before_the_flow_id_route(self, client):
        """Every static /api/flows/<segment> route must be declared before
        /api/flows/{flow_id}, or "quick" arrives as a flow id -- a 404 on a
        route that exists."""
        r = _post(client, subs=2, filters=["L"])
        assert r.status_code != 404, r.text


class TestTheRunIsTheSameHandler:
    """Driven through guards that live ONLY inside ``run_flow``.

    A copy-pasted start path would pass "it started" and fail every one of
    these, which is the point: the tests assert the SHAPE of the refusal, not
    merely that something was refused.
    """

    def _no_camera_needed(self, monkeypatch):
        monkeypatch.setattr(app_module.hub, "require", lambda *a, **k: None)

    def test_the_sun_cone_is_checked_on_this_route_too(self, client, monkeypatch):
        """The guard ``force`` cannot lift, because every other refusal costs a
        night and this one costs a sensor. It lives inside ``run_flow``."""
        from astrodeck.devices.base import DeviceError
        monkeypatch.setattr(
            app_module.hub, "_check_solar",
            lambda ra, dec: (_ for _ in ()).throw(
                DeviceError("target is 3.1 deg from the Sun")))
        r = _post(client, subs=4, filters=["L"], run=True)
        assert r.status_code == 409, r.text
        assert r.json()["detail"]["code"] == "sun_exclusion"

    def test_a_refused_run_still_reports_the_saved_flow(self, client, monkeypatch):
        """The save already happened. Throwing it away would discard work the
        operator asked for, and hiding the id would leave a flow in the library
        the sheet cannot offer to open."""
        from astrodeck.devices.base import DeviceError
        monkeypatch.setattr(
            app_module.hub, "_check_solar",
            lambda ra, dec: (_ for _ in ()).throw(DeviceError("near the Sun")))
        r = _post(client, subs=4, filters=["L"], run=True)
        detail = r.json()["detail"]
        assert detail.get("saved") is True and detail.get("flow_id")
        assert client.get(f"/api/flows/{detail['flow_id']}").status_code == 200

    def test_a_run_already_in_flight_is_a_409(self, client, monkeypatch):
        from astrodeck.devices.base import DeviceError
        self._no_camera_needed(monkeypatch)

        def _busy(*a, **k):
            raise DeviceError("a sequence is already running")

        monkeypatch.setattr(app_module.engine, "start", _busy)
        r = _post(client, subs=4, filters=["L"], run=True)
        assert r.status_code == 409, r.text
        assert "already running" in str(r.json()["detail"])

    def test_a_started_run_carries_run_flows_own_origin(self, client, monkeypatch):
        """``origin="flow"`` and ``origin_id`` are set by ``run_flow`` and by
        nothing else. A second start path would hand the engine a plan the
        session ledger cannot attribute to a flow."""
        seen: dict = {}
        self._no_camera_needed(monkeypatch)
        monkeypatch.setattr(app_module.engine, "start",
                            lambda plan, **kw: seen.update(plan=plan, **kw))
        r = _post(client, subs=4, filters=["L", "R"], run=True)
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["started"] is True
        assert seen["origin"] == "flow"
        assert seen["origin_id"] == body["flow"]["id"]
        assert seen["plan"].total_frames() == 8

    def test_starting_it_stamps_the_card_the_way_run_flow_does(self, client,
                                                               monkeypatch):
        """`last_run` had been on FlowRecord since the library shipped and
        nothing wrote it; the card said NEVER RUN forever. ``run_flow`` stamps
        it, so a quick flow that started must be stamped too."""
        self._no_camera_needed(monkeypatch)
        monkeypatch.setattr(app_module.engine, "start", lambda plan, **kw: None)
        fid = _post(client, subs=2, filters=["L"], run=True).json()["flow"]["id"]
        card = next(c for c in client.get("/api/flows").json() if c["id"] == fid)
        assert card["last_run"], "the card will read NEVER RUN on a flow that ran"

    def test_run_false_starts_nothing(self, client, monkeypatch):
        """The default. A save that quietly opened the shutter would be the
        worst possible reading of a button called Save."""
        started: list = []
        self._no_camera_needed(monkeypatch)
        monkeypatch.setattr(app_module.engine, "start",
                            lambda plan, **kw: started.append(plan))
        assert _post(client, subs=2, filters=["L"]).status_code == 200
        assert started == []
