"""The panel lane: which TARGET a capture or cycle stage belongs to (#151,
#189 U-09 part; spec 2026-09-23 flows mosaic, 1.3 item 1, 1.4 items 1-4, 1.5
and D2).

WHY THIS EXISTS. The compile used to hand every CAPTURE LOOP and FILTER CYCLE
to every target seen earlier in canvas order. For a mosaic that leaks: a
CAPTURE drawn after a second TARGET would be shot on all six M31 panels as
well. So in a graph with a multi-panel block, a stage belongs only to the
TARGET (or POOL) its flow wires lead back to through lane nodes, found by
``owner_of``, and the loop wire is the ``pass`` wire from the lane's tail into
that block's ``next``.

THE WORKED CASES live in ``fixtures/panel_lane_cases.json``, written from the
spec's table rather than generated by the code they grade, because the
TypeScript mirror (S3-U) grades itself against the same file. The named
mutants below were each run in a private scratch copy of ``server/``, never in
the shared tree (#254), and the failure each one produced is quoted verbatim
in the test that caught it.
"""
from __future__ import annotations

import ctypes
import json
import threading
from pathlib import Path

import pytest

from astrodeck.flows.compile import (
    compile_plan,
    is_multi_panel,
    lane_branched,
    lane_next,
    lane_tail,
    loop_wires,
    owner_of,
    panel_lane,
)
from astrodeck.flows.models import FlowEdge, FlowGraph, FlowNode

FIXTURE = Path(__file__).parent / "fixtures" / "panel_lane_cases.json"
CASES = json.loads(FIXTURE.read_text(encoding="utf-8"))["cases"]


def _case(case_id: str) -> dict:
    return next(c for c in CASES if c["id"] == case_id)


def _graph(case: dict) -> FlowGraph:
    return FlowGraph.model_validate(case["graph"])


def _n(nid, ntype, x=0.0, y=0.0, **params):
    return FlowNode(id=nid, type=ntype, x=x, y=y, params=params)


def _e(a, ap, b, bp, eid=None):
    kw = {"from": a, "fromPort": ap, "to": b, "toPort": bp}
    if eid is not None:
        kw["id"] = eid
    return FlowEdge(**kw)


def _steps_by_block(plan: dict) -> dict[str, list[list[str]]]:
    """Each block's compiled entries, as the stage node ids each one carries.
    A list per block, because a POOL emits one entry per member."""
    out: dict[str, list[list[str]]] = {}
    for t in plan["targets"]:
        out.setdefault(t["node_id"], []).append([s["node_id"] for s in t["steps"]])
    return out


def _id(node):
    return None if node is None else node.id


class _Runaway(BaseException):
    """Raised INTO a walk that overran its bound, to stop it."""


def _bounded(fn, what: str, timeout: float = 5.0):
    """``fn()``, run in a daemon thread and given ``timeout`` seconds.

    Every walk in this file goes through here because one fixture case is a
    flow cycle: without the seen-set a walk goes round it for ever, and a
    test that hangs is a test nobody reads. Bounded, the mutant FAILS with a
    sentence instead.

    THE OVERRUNNING THREAD IS STOPPED, not abandoned. Measured under the "no
    seen-set" mutant: two abandoned threads still spinning took three tests
    to 48 s and the file past 300 s, because every GIL release on the main
    thread (the conftest teardown's ctypes calls release it hundreds of times)
    then waits out a spinning thread's switch interval. So an overrun gets
    ``_Runaway`` raised inside it, which a pure-Python loop meets at its next
    bytecode check."""
    box: dict = {}

    def run():
        try:
            box["value"] = fn()
        except BaseException as exc:        # re-raised on the test's thread
            box["error"] = exc

    th = threading.Thread(target=run, daemon=True)
    th.start()
    th.join(timeout)
    if th.is_alive():
        ctypes.pythonapi.PyThreadState_SetAsyncExc(
            ctypes.c_ulong(th.ident), ctypes.py_object(_Runaway))
        th.join(timeout)
    assert "value" in box or "error" in box, \
        f"{what} did not return within {timeout:g} s"
    if isinstance(box.get("error"), _Runaway):
        raise AssertionError(f"{what} did not return within {timeout:g} s")
    if "error" in box:
        raise box["error"]
    return box["value"]


# ------------------------------------------------------------ the fixture

class TestTheWorkedCases:
    """Spec 1.5's four worked cases, a branched lane, a mid-lane pass wire and
    a flow cycle with no way in, each graded on its owners, its lane, its tail,
    its loop and its compile.

    Mutant "owner is any upstream TARGET" (the doctor's set walk: collect every
    node upstream along flow wires, through any type, and return the nearest
    TARGET or POOL) failed all three on dome-ends-the-lane, and only there:
        AssertionError: dome-ends-the-lane: ha
        assert 't' == None
        AssertionError: dome-ends-the-lane: t
        {'lane': ['cy', 'ha']} != {'lane': ['cy']}
        {'tail': 'ha'} != {'tail': 'cy'}
        AssertionError: dome-ends-the-lane
        assert {'t': [['cy', 'ha']]} == {'t': [['cy']]}

    The same three tests caught these, one line of each failure quoted:
        "no seen-set" [flow-cycle-with-no-way-in]:
            AssertionError: owner_of('a') did not return within 5 s
            AssertionError: the lane of 't' did not return within 5 s
        "legacy rule in mosaic graphs" [second-target-owns-the-capture]:
            {'m31': [['cy', 'ha']]} != {'m31': [['cy']]}
        "the tail is the deepest stage, branched or not" [branched-lane]:
            {'tail': 'ha'} != {'tail': None}
        "any pass wire from the lane into next" [mid-lane-pass-wire]:
            {'loop': True} != {'loop': False}
        "wire kinds ignored" [af-guide-cycle]:
            {'next': ['t', 'r']} != {'next': ['r']}
        "any node can be walked from" [af-guide-cycle]:
            {'tail': 'r'} != {'tail': 'cy'}
        "no scope notes" [second-target-owns-the-capture]:
            assert [] == ['ha']
        "a note for every scoped stage" [af-guide-cycle]:
            assert ['cy'] == []
    """

    @pytest.mark.parametrize("case", CASES, ids=lambda c: c["id"])
    def test_owner_of_every_lane_node(self, case):
        g = _graph(case)
        for nid, want in case["owners"].items():
            got = _bounded(lambda: _id(owner_of(g, nid)), f"owner_of({nid!r})")
            assert got == want, f"{case['id']}: {nid}"

    @pytest.mark.parametrize("case", CASES, ids=lambda c: c["id"])
    def test_the_lane_its_tail_and_its_loop(self, case):
        g = _graph(case)
        for oid, want in case["lanes"].items():
            owner = g.node(oid)
            got = _bounded(lambda: {
                "lane": [n.id for n in panel_lane(g, owner)],
                "tail": _id(lane_tail(g, owner)),
                "branched": lane_branched(g, owner),
                "loop": bool(loop_wires(g, owner)),
                "next": [n.id for n in lane_next(g, owner)],
            }, f"the lane of {oid!r}")
            assert got == want, f"{case['id']}: {oid}"

    @pytest.mark.parametrize("case", CASES, ids=lambda c: c["id"])
    def test_the_compile_scopes_every_stage(self, case):
        plan = _bounded(lambda: compile_plan(_graph(case), "n"), "compile_plan")
        want = {oid: [ids] for oid, ids in case["compile"]["steps"].items()}
        assert _steps_by_block(plan) == want, case["id"]
        assert [x["node_id"] for x in plan.get("notes", [])] == \
            case["compile"]["notes"], case["id"]

    def test_the_fixture_holds_the_cases_the_spec_names(self):
        """S3-U grades its mirror against this file, so a case quietly dropped
        here is a case dropped from both languages.

        Mutant of the FIXTURE (a scratch copy) "drop branched-lane" failed:
            AssertionError: assert {'af-guide-cy...-the-capture'} >=
            {'af-guide-cy...-the-capture'}
              Extra items in the right set:
              'branched-lane'
        """
        assert {c["id"] for c in CASES} >= {
            "af-guide-cycle", "cycle-then-capture",
            "second-target-owns-the-capture", "dome-ends-the-lane",
            "branched-lane", "mid-lane-pass-wire"}


# ------------------------------------------------------------- owner_of

class TestOwnerOfIsAChainWalk:

    def test_the_capture_after_the_dome_belongs_to_no_target(self):
        """TARGET -> CYCLE -> DOME -> CAPTURE. DOME ends the lane, so the
        CAPTURE belongs to nobody and must compile to nothing (M13 makes that
        loud). The doctor's set walk would find the TARGET upstream and hand
        the CAPTURE to all six panels, which is the leak this rule closes.

        Mutant "owner is any upstream TARGET" failed:
            AssertionError: assert 't' is None
        Mutant "legacy rule in mosaic graphs" failed:
            AssertionError: assert ['cy', 'ha'] == ['cy']
        """
        g = _graph(_case("dome-ends-the-lane"))
        assert _id(owner_of(g, "ha")) is None
        m31 = compile_plan(g, "n")["targets"][0]
        assert [s["node_id"] for s in m31["steps"]] == ["cy"]

    def test_a_legacy_slew_is_part_of_the_lane(self):
        """Every saved flow and every Example still draws SLEW + CENTER between
        the TARGET and its stages (it is legacy, not deleted, spec 1.7). If it
        ended the lane, every one of those stages would belong to no target.

        Mutant "SLEW is not a lane node" failed:
            AssertionError: assert None == 't'
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2), _n("s", "slew", x=100),
                   _n("af", "autofocus", x=200), _n("g", "guide", x=300),
                   _n("c", "capture", x=400)],
            edges=[_e("t", "target", "s", "run"), _e("s", "centered", "af", "run"),
                   _e("af", "focused", "g", "run"), _e("g", "guiding", "c", "run")])
        assert _id(owner_of(g, "c")) == "t"

    def test_a_flow_cycle_does_not_hang_the_walk(self):
        """Two stages feed each other and nothing feeds them. Each has exactly
        one flow parent, so a walk with no memory of where it has been goes
        round for ever. Run in a thread and bounded, so the mutant FAILS
        rather than hanging the suite.

        Mutant "no seen-set" failed (the walk never returned):
            AssertionError: owner_of on a flow cycle did not return within 5 s
        """
        g = _graph(_case("flow-cycle-with-no-way-in"))
        got = _bounded(lambda: {"a": _id(owner_of(g, "a")),
                                "b": _id(owner_of(g, "b")),
                                "tail": _id(lane_tail(g, g.node("t")))},
                       "owner_of on a flow cycle")
        assert got == {"a": None, "b": None, "tail": None}

    def test_two_flow_parents_have_no_owner(self):
        """Only a graph built outside the editor has two wires into one flow
        input (validation refuses it), but the compile routes still compile
        half-built graphs. Two parents are two answers; picking one would hand
        the stage to a block by edge order, so there is no owner.

        Mutant "the first parent wins" failed, and so did "owner is any
        upstream TARGET":
            AssertionError: assert 'a' is None
        """
        g = FlowGraph(
            nodes=[_n("a", "target", rows=3, cols=2), _n("b", "target", y=100),
                   _n("c", "capture", x=200)],
            edges=[_e("a", "target", "c", "run"), _e("b", "target", "c", "run")])
        assert _id(owner_of(g, "c")) is None

    def test_the_same_parent_wired_twice_is_still_one_chain(self):
        """Control for the rule above: a duplicated wire from ONE parent names
        one block, so the owner is not ambiguous.

        Mutant "a parent wired twice is two parents" failed:
            AssertionError: assert None == 'a'
        """
        g = FlowGraph(
            nodes=[_n("a", "target", rows=3, cols=2), _n("c", "capture", x=200)],
            edges=[_e("a", "target", "c", "run", "w1"),
                   _e("a", "target", "c", "run", "w2")])
        assert _id(owner_of(g, "c")) == "a"

    def test_a_node_that_ends_the_lane_is_owned_by_nobody(self):
        """DOME, REPORT and a second TARGET are not lane nodes; asking who
        owns one is asking who owns a node outside every lane. Controls: none
        of them may be answered with the block above them.

        Mutant "any node can be walked from" failed:
            AssertionError: assert FlowNode(id='t', type='target', x=0.0,
            y=0.0, params={'name': 'M31', 'rows': 3, 'cols': 2}) is None
        """
        g = _graph(_case("dome-ends-the-lane"))
        assert owner_of(g, "dm") is None
        g3 = _graph(_case("second-target-owns-the-capture"))
        assert owner_of(g3, "m33") is None
        g1 = _graph(_case("af-guide-cycle"))
        assert owner_of(g1, "r") is None
        assert owner_of(g1, "no-such-node") is None

    def test_a_stage_under_a_pool_belongs_to_the_pool(self):
        """Mutant "POOL is not an owner" failed:
            AssertionError: assert None == 'p'
        """
        g = FlowGraph(
            nodes=[_n("p", "pool", members="A, B"), _n("g", "guide", x=100),
                   _n("c", "capture", x=200)],
            edges=[_e("p", "target", "g", "run"), _e("g", "guiding", "c", "run")])
        assert _id(owner_of(g, "c")) == "p"

    def test_the_loop_wire_is_not_a_step_of_the_cursor(self):
        """The loop wire points backwards from the tail into the TARGET. It is
        an event ("whenever a pass is done"), so reading it as a flow wire
        would make the TARGET a child of its own tail and list it as what
        runs after the mosaic.

        Mutant "wire kinds ignored" (every wire is a flow wire) failed:
            AssertionError: assert ['t', 'r'] == ['r']
        """
        g = _graph(_case("af-guide-cycle"))
        assert [n.id for n in lane_next(g, g.node("t"))] == ["r"]
        assert _id(owner_of(g, "cy")) == "t"

    def test_a_flow_output_dropped_on_next_is_not_a_step(self):
        """FILTER CYCLE 'all done' dropped on TARGET 'next panel' crosses the
        flow/event boundary, which validation refuses and a half-built graph
        can still hold. Read by its source port alone it would be a flow step
        into the TARGET, and the TARGET would run after its own lane.

        Mutant "a wire is a flow wire by its source port alone" failed:
            AssertionError: assert ['t'] == []
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2), _n("cy", "cycle", x=200)],
            edges=[_e("t", "target", "cy", "run"),
                   _e("cy", "complete", "t", "next")])
        assert [n.id for n in lane_next(g, g.node("t"))] == []
        assert _id(owner_of(g, "cy")) == "t"


# ---------------------------------------------------------- the lane shape

class TestTheLaneShape:

    def test_a_branched_lane_has_no_tail(self):
        """AF feeds both CYCLE and CAPTURE Ha: two last stages. Choosing one
        would put the loop wire on a stage the operator did not mean (M12).

        Mutant "the tail is the deepest stage, branched or not" failed:
            AssertionError: assert 'ha' is None
        """
        g = _graph(_case("branched-lane"))
        t = g.node("t")
        assert lane_branched(g, t) is True
        assert _id(lane_tail(g, t)) is None

    def test_fan_out_from_the_target_itself_is_a_branch(self):
        """Spec 1.5 item 4: "no fan-out from the TARGET or between lane nodes".

        Mutant "the tail is the deepest stage, branched or not" failed:
            AssertionError: assert FlowNode(id='c', type='capture', x=200.0,
            y=100.0, params={}) is None
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2),
                   _n("cy", "cycle", x=200), _n("c", "capture", x=200, y=100)],
            edges=[_e("t", "target", "cy", "run"), _e("t", "target", "c", "run")])
        assert lane_branched(g, g.node("t")) is True
        assert lane_tail(g, g.node("t")) is None

    def test_a_non_lane_sibling_is_not_a_branch(self):
        """Control: TARGET feeds a CYCLE and a DOME. DOME is not a lane node,
        so the lane is still one chain and its tail is the CYCLE.

        Mutant "any node can be walked from" (DOME joins the lane) failed:
            AssertionError: assert True is False
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2),
                   _n("cy", "cycle", x=200), _n("dm", "dome", x=200, y=100)],
            edges=[_e("t", "target", "cy", "run"), _e("t", "target", "dm", "run")])
        assert lane_branched(g, g.node("t")) is False
        assert _id(lane_tail(g, g.node("t"))) == "cy"

    def test_an_empty_lane(self):
        """A TARGET wired straight to a REPORT owns nothing: no tail, no loop,
        and nothing to call branched.

        Mutant "any node can be walked from" failed:
            AssertionError: assert ([FlowNode(id=...0, params={})] == []
              Left contains one more item: FlowNode(id='r', type='report',
              x=100.0, y=0.0, params={})
        """
        g = FlowGraph(nodes=[_n("t", "target", rows=3, cols=2), _n("r", "report", x=100)],
                      edges=[_e("t", "target", "r", "session")])
        t = g.node("t")
        assert panel_lane(g, t) == [] and lane_tail(g, t) is None
        assert lane_branched(g, t) is False and loop_wires(g, t) == []

    def test_what_runs_next_names_each_node_once_in_canvas_order(self):
        """The tail's 'all done' wired twice to one REPORT (a duplicate a
        half-built graph can hold) is still one thing that runs next, and two
        different next nodes read in canvas order, as the compile walks them.

        Mutant "lane_next keeps duplicate wires" failed:
            AssertionError: assert ['dm', 'r', 'r'] == ['dm', 'r']
              Left contains one more item: 'r'
        Mutant "lane_next in wire order" failed:
            AssertionError: assert ['r', 'dm'] == ['dm', 'r']
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2), _n("cy", "cycle", x=200),
                   _n("r", "report", x=600), _n("dm", "dome", x=400, y=200)],
            edges=[_e("t", "target", "cy", "run"),
                   _e("cy", "complete", "r", "session", "w1"),
                   _e("cy", "complete", "r", "session", "w2"),
                   _e("cy", "complete", "dm", "run", "w3")])
        assert [n.id for n in lane_next(g, g.node("t"))] == ["dm", "r"]


# ------------------------------------------------------------ the loop wire

class TestTheLoopWire:

    def test_the_loop_is_the_pass_wire_from_the_tail_into_next(self):
        """Mutant "any node can be walked from" (REPORT becomes the tail)
        failed:
            AssertionError: assert [] == ['loop']
        """
        g = _graph(_case("af-guide-cycle"))
        assert [e.id for e in loop_wires(g, g.node("t"))] == ["loop"]

    def test_a_pass_wire_from_a_mid_lane_stage_is_not_the_loop(self):
        """CAPTURE Ha comes after the CYCLE the wire leaves, so the loop would
        rotate panels before CAPTURE Ha was ever shot on them (M12).

        Mutant "any pass wire from the lane into next" failed:
            AssertionError: assert ['early'] == []
        """
        g = _graph(_case("mid-lane-pass-wire"))
        assert [e.id for e in loop_wires(g, g.node("t"))] == []

    def test_a_pass_wire_into_another_block_is_nobodys_loop(self):
        """The CYCLE is M31's tail, but its pass wire goes into M33's next.
        It closes neither circle (M4: "this wire does nothing").

        Mutant "loop wire into any block's next" failed:
            AssertionError: assert [FlowEdge(id=...oPort='next')] == []
              Left contains one more item: FlowEdge(id='stray', from_='cy',
              fromPort='pass', to='m33', toPort='next')
        """
        c = _case("second-target-owns-the-capture")
        g = _graph(c).model_copy(update={"edges": [
            *[e for e in _graph(c).edges if e.id != "loop"],
            _e("cy", "pass", "m33", "next", "stray")]})
        assert loop_wires(g, g.node("m31")) == []
        assert loop_wires(g, g.node("m33")) == []

    @pytest.mark.parametrize("from_port,to_port", [
        ("frame", "next"),      # the graded-frame event, not the pass
        ("pass", "arm"),        # into the flow input, not next
    ])
    def test_the_ports_are_part_of_the_loop(self, from_port, to_port):
        """Controls: the wire must leave ``pass`` and enter ``next``.

        Mutant "loop wire from any port of the tail" failed [frame-next]:
            Left contains one more item: FlowEdge(id='2233723b9f6e',
            from_='cy', fromPort='frame', to='t', toPort='next')
        Mutant "loop wire into any port of the block" failed [pass-arm]:
            Left contains one more item: FlowEdge(id='e1cdeeb59671',
            from_='cy', fromPort='pass', to='t', toPort='arm')
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2), _n("cy", "cycle", x=200)],
            edges=[_e("t", "target", "cy", "run"),
                   _e("cy", from_port, "t", to_port)])
        assert loop_wires(g, g.node("t")) == []


# ------------------------------------------------------- scoping in compile

class TestScopingInTheCompile:

    def test_the_capture_after_a_second_target_stays_off_the_mosaic(self):
        """Worked case 3. Under the canvas-order rule the CAPTURE after
        TARGET(M33) is appended to every target seen so far, M31 included, so
        six M31 panels would each owe it.

        Mutant "legacy rule in mosaic graphs" failed:
            AssertionError: assert ['cy', 'ha'] == ['cy']
        """
        plan = compile_plan(_graph(_case("second-target-owns-the-capture")), "n")
        by = {t["node_id"]: [s["node_id"] for s in t["steps"]] for t in plan["targets"]}
        assert by["m31"] == ["cy"]
        assert by["m33"] == ["ha"]

    def test_a_two_lane_flow_with_a_mosaic_scopes_by_wire(self):
        """Two separate lanes, laid out so canvas order interleaves them: the
        mosaic's TARGET, the single TARGET, then each one's stage. By canvas
        order both stages would reach both targets.

        Mutant "legacy rule in mosaic graphs" failed:
            AssertionError: assert {'a': [['cy',...[['cy', 'c']]} ==
            {'a': [['cy']], 'b': [['c']]}
              {'a': [['cy', 'c']]} != {'a': [['cy']]}
              {'b': [['cy', 'c']]} != {'b': [['c']]}
        """
        g = FlowGraph(
            nodes=[_n("a", "target", x=100, name="M31", rows=2, cols=2),
                   _n("b", "target", x=200, y=300, name="M33"),
                   _n("cy", "cycle", x=300, plan="L 60, R 60"),
                   _n("c", "capture", x=400, y=300, filter="Ha", count=10)],
            edges=[_e("a", "target", "cy", "run"), _e("b", "target", "c", "run"),
                   _e("cy", "pass", "a", "next")])
        assert _steps_by_block(compile_plan(g, "n")) == {
            "a": [["cy"]], "b": [["c"]]}

    def test_every_pool_member_gets_its_own_lanes_stage_only(self):
        """A POOL lane beside a mosaic: both members carry the pool's CAPTURE,
        in their own dicts, and none of the mosaic's CYCLE.

        Mutant "legacy rule in mosaic graphs" failed:
            {'t': [['cy', 'c']]} != {'t': [['cy']]}
            {'p': [['cy', 'c'], ['cy', 'c']]} != {'p': [['c'], ['c']]}
        Mutant "POOL is not an owner" failed:
            AssertionError: assert {'p': [[], []], 't': [['cy']]} ==
            {'p': [['c'],...'t': [['cy']]}
        """
        g = FlowGraph(
            nodes=[_n("t", "target", x=0, name="M31", rows=3, cols=2),
                   _n("p", "pool", x=100, y=300, members="A, B"),
                   _n("cy", "cycle", x=200, plan="L 60"),
                   _n("c", "capture", x=300, y=300, count=5)],
            edges=[_e("t", "target", "cy", "run"), _e("p", "target", "c", "run")])
        plan = compile_plan(g, "n")
        assert _steps_by_block(plan) == {"t": [["cy"]], "p": [["c"], ["c"]]}
        a, b = [t for t in plan["targets"] if t["node_id"] == "p"]
        a["steps"][0]["count"] = 999
        assert b["steps"][0]["count"] == 5

    def test_with_no_multi_panel_block_the_canvas_order_rule_stays(self):
        """Worked case 3's graph with M31 made 1x1. The legacy rule is kept byte
        for byte, leak and all (the leak is its own defect, I-05): the CAPTURE
        after M33 still reaches M31, and the compile says nothing new.

        Mutant "the wire rule in every graph" failed (the only test that
        catches it: all seven Examples compile the same under either rule, so
        the Examples control cannot):
            AssertionError: assert ['cy'] == ['cy', 'ha']
        Mutant "an empty notes list on every compile" failed:
            AssertionError: assert 'notes' not in {...}
        """
        c = _case("second-target-owns-the-capture")
        nodes = [n if n["id"] != "m31" else {**n, "params": {"name": "M31"}}
                 for n in c["graph"]["nodes"]]
        g = FlowGraph.model_validate({**c["graph"], "nodes": nodes})
        plan = compile_plan(g, "n")
        by = {t["node_id"]: [s["node_id"] for s in t["steps"]] for t in plan["targets"]}
        assert by["m31"] == ["cy", "ha"]
        assert by["m33"] == ["ha"]
        assert "notes" not in plan

    @pytest.mark.parametrize("rows,cols,multi", [
        (None, None, False),        # absent means 1, which is every saved flow
        (1, 1, False),
        (3, 1, True),
        (1, 3, True),               # a single row of three is still a mosaic
        ("2", "2", True),           # the inspector may hand a number as text
        ("abc", 4, True),           # unreadable reads as 1, the other still counts
        ("abc", "", False),
        (0, 5, True),               # 0 is not a grid size; it reads as 1
        (-3, -3, False),
        (1.9, 1, False),            # a grid is whole panels: 1.9 rows is 1
        (float("nan"), 2, True),
        (float("inf"), 1, False),
        (True, 1, False),
    ])
    def test_rows_and_cols_are_read_defensively(self, rows, cols, multi):
        """Spec 3.1: missing rows and cols mean 1, the old meaning. Anything
        that is not a whole number of at least 1 reads as 1, so a hand-edited
        file cannot switch a graph's scoping rule with a string.

        Mutant "rows only" (cols ignored) failed four cases, each with
            AssertionError: assert False is True
        on [1-3-True], [abc-4-True], [0-5-True] and [nan-2-True].
        """
        params = {k: v for k, v in (("rows", rows), ("cols", cols)) if v is not None}
        assert is_multi_panel(_n("t", "target", **params)) is multi

    def test_only_a_target_is_a_mosaic(self):
        """A POOL has no grid; rows and cols on one (a hand-edited file) must
        not flip the whole graph to the wire rule. Control.

        Mutant "any node type can be a mosaic" failed:
            AssertionError: assert True is False
        """
        assert is_multi_panel(_n("p", "pool", rows=3, cols=2)) is False


class TestTheCompileSaysWhenTheRulesDiffer:

    def test_a_narrowed_stage_is_named(self):
        """Mutant "no scope notes" failed:
            KeyError: 'notes'
        """
        plan = compile_plan(_graph(_case("second-target-owns-the-capture")), "n")
        (note,) = plan["notes"]
        assert note["node_id"] == "ha" and note["level"] == "note"
        assert "CAPTURE LOOP Ha" in note["text"]
        assert "TARGET M33" in note["text"] and "M31" in note["text"]

    def test_an_unowned_stage_is_named_louder(self):
        """It compiles to nothing, which the canvas-order rule never did.

        Mutant "no scope notes" failed:
            KeyError: 'notes'
        Mutant "every scope note is a note" failed:
            AssertionError: assert ('ha' == 'ha'
                ha and 'note' == 'warn'
        """
        plan = compile_plan(_graph(_case("dome-ends-the-lane")), "n")
        (note,) = plan["notes"]
        assert note["node_id"] == "ha" and note["level"] == "warn"
        assert "CAPTURE LOOP Ha belongs to no TARGET" in note["text"]
        assert "M31" in note["text"]

    def test_a_note_names_each_target_once(self):
        """Two single TARGETs that share a name are two blocks but one word
        to the operator; the note lists the names canvas order would have
        used, each once.

        Mutant "entry names not deduplicated" failed:
            AssertionError: assert 'would have been shot on M31, M33.' in
            'CAPTURE LOOP Ha belongs to no TARGET, ... By canvas order it
            would have been shot on M31, M33, M33. Give it a TARGET.'
        """
        c = _case("dome-ends-the-lane")
        g = FlowGraph.model_validate({**c["graph"], "nodes": [
            *c["graph"]["nodes"],
            # right of the CYCLE and left of the CAPTURE in canvas order, so
            # only the CAPTURE is one canvas order would have given them
            {"id": "b", "type": "target", "x": 300, "y": 300,
             "params": {"name": "M33"}},
            {"id": "b2", "type": "target", "x": 350, "y": 300,
             "params": {"name": "M33"}}]})
        (note,) = compile_plan(g, "n")["notes"]
        assert note["node_id"] == "ha"
        assert "would have been shot on M31, M33." in note["text"]

    def test_a_stage_both_rules_agree_on_is_not_mentioned(self):
        """Control: in worked case 1 the CYCLE goes to M31 by either rule, so
        there is no key at all (absent, never an empty list, as ``campaign``).

        Mutant "a note for every scoped stage" failed, and so did "an empty
        notes list on every compile":
            AssertionError: assert 'notes' not in {'automation': {},
            'instructions': [{'action': 'target', 'to_port': 'next', 'when':
            'cycle.pass'}], 'name': 'n', 'note...
        """
        plan = compile_plan(_graph(_case("af-guide-cycle")), "n")
        assert "notes" not in plan
