# Copyright (c) 2026 James Penick
# SPDX-License-Identifier: Apache-2.0
"""#195 (WP-85): Tonight's copy about what happens on a LATER night follows the
plan's `resume_across_nights`, so it never promises what the engine has been
told not to do.

Before this, three sentences on the Tonight panel said a subsequent night resumes
the flow: the STORY tab's budget rows ("the run resumes the remainder next
clear night"), the CAMPAIGN tab's closing note (`_DAWN`: "Each dusk resumes
where the session log left off") and the brief's campaign clause ("the flow
re-arms at the next dusk"). A flow that turned DUSK WINDOW's Automatic resume
Off is disarmed where its night ends (`_finalize_report`), so all three were
a claim nothing keeps for it. They now say what an Off flow does: a later
night does not resume by itself, and CONTINUE is the way.

Every ON flow's sentences are unchanged, word for word: the fixtures
(`tonight_mosaic_2x3.json`, `tonight_budget_for_these_targets.json`) are
regenerated by their recipes and byte-diffed, and the diff holds only the
campaign note a flow with no campaign reads (see below).

The CAMPAIGN tab's note for a flow that is not a campaign used to read
"Single-night flow - set DUSK WINDOW -> Repeat to make this a campaign". The
editor no longer offers Repeat, and a flow nobody has touched IS resuming, so
it says which of the two the flow is and promises no campaign (`is_campaign`
is still keyed on `repeat` until `repeat` is retired, a later change).

The harness is ``test_flows_tonight_cycle_budget.py``'s: a synthetic site (40 N
105 W, not the observatory's), the hub pinned to it, the panel stamp stood in
for, and one pinned ``now`` (the story reads ``now`` and nothing else here is
clocked).

NAMED MUTANTS (each run from a byte backup inside this worktree, restored and
sha256-compared, the mutant text grepped out afterwards; the failure is
quoted in the docstring of the test that catches it):

* "tonight copy ignores the plan": `_story`'s ``resumes`` read as True;
* "campaign note ignores the option": `_campaign`'s ``resumes`` read as True.
"""
from __future__ import annotations

import datetime as _dt

import pytest

from astrodeck.catalog import framing
from astrodeck.flows.examples import examples
from astrodeck.flows.models import FlowEdge, FlowGraph, FlowNode
from astrodeck.flows.tonight import (_DAWN, _DAWN_OFF, _NO_LATER_RESUME,
                                     _campaign, brief, resolve_tonight)
from astrodeck.hub import Hub

SITE = {"latitude": 40.0, "longitude": -105.0, "elevation_m": 1600.0,
        "is_default": False}
TWILIGHT = -12.0
#: Late afternoon at the site (13:00 local solar), so "tonight" is ahead.
JUNE = _dt.datetime(2026, 6, 15, 20, 0, tzinfo=_dt.timezone.utc).timestamp()

RESUMES = "the run resumes the remainder next clear night"
OFF = "a subsequent night does not resume by itself; CONTINUE it by hand"


@pytest.fixture(autouse=True)
def synthetic_hub_and_no_ephemeris(monkeypatch):
    monkeypatch.setattr(Hub, "site", property(lambda self: {
        "name": "synthetic", **SITE, "horizon_min_deg": 0.0}))

    async def stamp(panels, date, *, site=None):
        for p in panels:
            p["transit_alt"] = 45.0
    monkeypatch.setattr(framing, "_stamp_transit_alt", stamp)


def _n(nid, ntype, x=0.0, **params):
    return FlowNode(id=nid, type=ntype, x=x, y=0.0, params=params)


def _e(a, ap, b, bp):
    return FlowEdge(**{"from": a, "fromPort": ap, "to": b, "toPort": bp})


def _goal_flow(**dusk) -> FlowGraph:
    """dusk -> TARGET M31 -> CAPTURE of Ha with a 2 h goal, which is what
    gives the STORY tab a goal row."""
    return FlowGraph(
        nodes=[_n("d", "dusk", offset=-30, stop="Dawn", minAlt=30, **dusk),
               _n("t", "target", 100, name="M31", ra="00h 42m 44s",
                  dec="+41 16 09"),
               _n("c", "capture", 200, filter="Ha", exposure=900, gain=100,
                  bin="1", count=8, goal=2)],
        edges=[_e("d", "window", "t", "arm"), _e("t", "target", "c", "run")])


def _tonight(graph):
    """With a ledger, because the sentence about the remainder is only said
    when there are captured totals to say it over."""
    return resolve_tonight(graph, SITE, now=JUNE, twilight_deg=TWILIGHT,
                           banked=lambda: {"Ha": 0.5})


def _time_rows(out) -> list[str]:
    return [s["msg"] for s in out["story"] if s["label"] == "TIME"]


def _example(flow_id: str) -> FlowGraph:
    return next(e for e in examples() if e.id == flow_id).graph.model_copy(
        deep=True)


def _set_dusk(graph: FlowGraph, **params) -> FlowGraph:
    for n in graph.nodes:
        if n.type == "dusk":
            n.params.update(params)
    return graph


# ================================================================ the STORY

def test_a_flow_that_resumes_says_the_run_resumes_the_remainder():
    """The control, and the sentence every ON flow has always read, whatever
    the DUSK WINDOW says or does not."""
    for dusk in ({}, {"autoResume": "On"}, {"repeat": "Single night"}):
        rows = _time_rows(_tonight(_goal_flow(**dusk)))
        assert len(rows) == 1 and rows[0].endswith(RESUMES), (dusk, rows)


def test_an_off_flow_does_not_say_the_run_resumes():
    """THE STORY TAB READS THE PLAN. With Automatic resume Off the plan carries
    ``resume_across_nights: false``, and the budget row says what happens to the
    remainder instead: nothing by itself, and CONTINUE.

    MUTANT "tonight copy ignores the plan" (`_story`'s ``resumes`` read as
    True) turned this red, run from a byte backup and restored and
    sha256-verified afterwards:

        AssertionError: ['Ha: 0.5 h captured for these targets / 2 h goal -
        tonight adds ~2 h; the run resumes the remainder next clear night']
        assert False
         +  where False = ....endswith('a subsequent night does not resume by
        itself; CONTINUE it by hand')
    """
    rows = _time_rows(_tonight(_goal_flow(autoResume="Off")))
    assert len(rows) == 1, rows
    assert rows[0].endswith(OFF), rows
    assert "resumes the remainder" not in rows[0], rows


def test_a_cycle_row_of_an_off_flow_says_it_too():
    """The FILTER CYCLE's row has its own sentence (S4 orchestrator ruling 5) and the same
    tail: the eighth Example, with a ledger so the tail is printed."""
    banked = {"L": 1.5, "R": 0.5}
    on = resolve_tonight(_example("example-m31-mosaic"), SITE, now=JUNE,
                         twilight_deg=TWILIGHT, hop_cost_s=160.0,
                         banked=lambda: banked)
    off = resolve_tonight(
        _set_dusk(_example("example-m31-mosaic"), autoResume="Off"), SITE,
        now=JUNE, twilight_deg=TWILIGHT, hop_cost_s=160.0,
        banked=lambda: banked)
    (on_row,), (off_row,) = _time_rows(on), _time_rows(off)
    assert on_row.endswith(RESUMES), on_row
    assert off_row.endswith(OFF), off_row
    # Nothing else in the row moved: the two rows are one sentence but its tail.
    assert on_row[:-len(RESUMES)] == off_row[:-len(OFF)]


# ============================================================ the CAMPAIGN tab

def test_a_pool_flow_that_resumes_says_so_and_names_no_repeat():
    """example-pool is a pool that resumes, and the note says that rather than
    the advice it used to give (set DUSK WINDOW -> Repeat), which points at a
    control the editor no longer has.

    RE-PINNED FOR BACKLOG WP-118 (#195, wave 16 integration). This case said
    example-pool was "not a campaign by the old key, but it IS resuming" and
    pinned the "Automatic resume is on" sentence. A campaign is a pool in a
    flow whose Automatic resume is On now (`compile.campaign_block`), so
    example-pool IS a campaign and its note ends with the campaign's own
    dawn sentence (`_DAWN`: each dusk resumes where the log left off); the "on"
    sentence is reached by a pool with NO DUSK WINDOW, which carries no
    opinion about resuming, and is pinned here on that flow."""
    c = _campaign(_example("example-pool"), None)
    assert c["has_pool"] is True and c["is_campaign"] is True
    assert c["note"].endswith(_DAWN), c["note"]
    assert "Repeat" not in c["note"] and "Single-night" not in c["note"]
    bare = _example("example-pool")
    bare.nodes = [n for n in bare.nodes if n.type != "dusk"]
    c = _campaign(bare, None)
    assert c["has_pool"] is True and c["is_campaign"] is False
    assert c["note"] == ("Automatic resume is on (DUSK WINDOW): a subsequent "
                         "night resumes this flow where the session log left "
                         "off.")
    assert "Repeat" not in c["note"] and "Single-night" not in c["note"]


def test_a_pool_flow_that_is_off_says_so_and_does_not_promise_a_campaign():
    """The note names the option and what to do about it, and does not
    promise a campaign. (It once added "`is_campaign` is still keyed on
    `repeat`, so flipping the option would not do that"; since WP-118 turning
    the option on DOES make this pool flow a campaign, which the note does not
    need to say: it says what to do, and the CAMPAIGN tab says the rest.)"""
    c = _campaign(_set_dusk(_example("example-pool"), autoResume="Off"), None)
    assert c["has_pool"] is True and c["is_campaign"] is False
    assert _NO_LATER_RESUME in c["note"], c["note"]
    assert "Automatic resume is off" in c["note"], c["note"]
    assert "campaign" not in c["note"], c["note"]


def test_a_campaign_that_resumes_keeps_the_dawn_sentence_word_for_word():
    """`_DAWN` is unchanged (another file asserts on it), and every campaign
    note an ON flow reads still ends with it."""
    assert _DAWN.endswith("Each dusk resumes where the session log left off.")
    c = _campaign(_example("example-campaign"), None)
    assert c["is_campaign"] is True
    assert c["note"].endswith(_DAWN), c["note"]


def test_a_campaign_that_is_off_says_a_later_night_does_not_resume():
    """A pool flow that turned Automatic resume Off says a later night does
    not resume it, and stops promising that each dusk resumes.

    RE-PINNED FOR BACKLOG WP-118 (#195, wave 16 integration). This case said
    "the campaign block is still keyed on `repeat` until it is retired, so
    this is still a campaign". It is retired: a pool flow with Automatic
    resume Off is told not to come back, so it is NO campaign
    (`compile.campaign_block`), and the sentence it reads is the generic Off
    note of the not-a-campaign branch (`_NO_LATER_RESUME`), the one the pool
    case above pins.

    MUTANT "campaign note ignores the option" (`_campaign`'s ``resumes`` read
    as True) turned this red, run from a byte backup and restored and
    sha256-verified afterwards:

        AssertionError: ... Each dusk resumes where the session log left off.
        assert False
         +  where False = ....endswith('... A subsequent night does not resume by
        itself; CONTINUE it by hand.')
    """
    c = _campaign(_set_dusk(_example("example-campaign"), autoResume="Off"),
                  None)
    assert c["has_pool"] is True and c["is_campaign"] is False
    assert _NO_LATER_RESUME in c["note"], c["note"]
    assert "Each dusk resumes" not in c["note"], c["note"]


def test_a_mosaic_with_no_pool_of_an_off_flow_ends_its_note_the_same_way():
    """The pool-less mosaic's note is `<panels> <not forecast> <dawn>`; only
    the last part follows the option."""
    on = _campaign(_example("example-m31-mosaic"), None)
    off = _campaign(_set_dusk(_example("example-m31-mosaic"),
                              autoResume="Off"), None)
    assert on["has_pool"] is False and on["note"].endswith(_DAWN), on["note"]
    assert off["note"].endswith(_DAWN_OFF), off["note"]
    assert on["note"][:-len(_DAWN)] == off["note"][:-len(_DAWN_OFF)]


def test_the_two_off_sentences_agree():
    """ONE PHRASE, said by both tabs, so the page cannot tell an operator two
    things about the same flow."""
    assert _NO_LATER_RESUME == OFF
    assert _DAWN_OFF.endswith("A " + OFF[2:] + ".")


# ================================================================ the brief

def test_a_campaign_that_is_off_does_not_say_it_re_arms():
    """`brief`'s campaign clause ("the flow re-arms at the next dusk and
    resumes mid-cycle") is a promise an Off flow does not make."""
    on = brief(_example("example-campaign"))
    off = brief(_set_dusk(_example("example-campaign"), autoResume="Off"))
    assert "re-arms at the next dusk" in on
    assert "re-arms" not in off, off
