# Copyright (c) 2026 James Penick
# SPDX-License-Identifier: Apache-2.0
"""The panel lane: which TARGET a capture or cycle stage belongs to (#151,
#189 U-09 part; spec 2026-09-23 flows mosaic, 1.3 item 1, 1.4 items 1-4, 1.5
and D2).

WHY THIS EXISTS. The compile used to hand every CAPTURE LOOP and FILTER CYCLE
to every target seen earlier in canvas order. For a mosaic that leaks: a
CAPTURE drawn after a second TARGET would be shot on all six M31 panels as
well. So in a graph with a multi-panel block, a stage belongs only to the
TARGET (or POOL) its flow wires lead back to through lane nodes, found by
``owner_of``, and the loop wire is the ``pass`` wire from the lane's tail into
that block's ``next``.

THE WORKED CASES live in ``fixtures/panel_lane_cases.json``, written from the
spec's table rather than generated by the code they grade, because the
TypeScript mirror (S3-U) grades itself against the same file. The named
mutants below were each run in a private scratch copy of ``server/``, never in
the shared tree (#254), and the failure each one produced is quoted verbatim
in the test that caught it.
"""
from __future__ import annotations

import ctypes
import json
import threading
from pathlib import Path

import pytest

from astrodeck.flows.compile import (
    compile_plan,
    is_multi_panel,
    lane_branched,
    lane_next,
    lane_refusals,
    lane_tail,
    loop_wires,
    owner_of,
    panel_lane,
)
from astrodeck.flows.models import FlowEdge, FlowGraph, FlowNode

FIXTURE = Path(__file__).parent / "fixtures" / "panel_lane_cases.json"
_FIXTURE_JSON = json.loads(FIXTURE.read_text(encoding="utf-8"))
CASES = _FIXTURE_JSON["cases"]
LOOP_CASES = _FIXTURE_JSON["loop_cases"]


def _case(case_id: str) -> dict:
    return next(c for c in CASES if c["id"] == case_id)


def _graph(case: dict) -> FlowGraph:
    return FlowGraph.model_validate(case["graph"])


def _n(nid, ntype, x=0.0, y=0.0, **params):
    return FlowNode(id=nid, type=ntype, x=x, y=y, params=params)


def _e(a, ap, b, bp, eid=None):
    kw = {"from": a, "fromPort": ap, "to": b, "toPort": bp}
    if eid is not None:
        kw["id"] = eid
    return FlowEdge(**kw)


def _steps_by_block(plan: dict) -> dict[str, list[list[str]]]:
    """Each block's compiled entries, as the stage node ids each one carries.
    A list per block, because a POOL emits one entry per member."""
    out: dict[str, list[list[str]]] = {}
    for t in plan["targets"]:
        out.setdefault(t["node_id"], []).append([s["node_id"] for s in t["steps"]])
    return out


def _id(node):
    return None if node is None else node.id


class _Runaway(BaseException):
    """Raised INTO a walk that overran its bound, to stop it."""


def _bounded(fn, what: str, timeout: float = 5.0):
    """``fn()``, run in a daemon thread and given ``timeout`` seconds.

    Every walk in this file goes through here because one fixture case is a
    flow cycle: without the seen-set a walk goes round it for ever, and a
    test that hangs is a test nobody reads. Bounded, the mutant FAILS with a
    sentence instead.

    THE OVERRUNNING THREAD IS STOPPED, not abandoned. Measured under the "no
    seen-set" mutant: two abandoned threads still spinning took three tests
    to 48 s and the file past 300 s, because every GIL release on the main
    thread (the conftest teardown's ctypes calls release it hundreds of times)
    then waits out a spinning thread's switch interval. So an overrun gets
    ``_Runaway`` raised inside it, which a pure-Python loop meets at its next
    bytecode check."""
    box: dict = {}

    def run():
        try:
            box["value"] = fn()
        except BaseException as exc:        # re-raised on the test's thread
            box["error"] = exc

    th = threading.Thread(target=run, daemon=True)
    th.start()
    th.join(timeout)
    if th.is_alive():
        ctypes.pythonapi.PyThreadState_SetAsyncExc(
            ctypes.c_ulong(th.ident), ctypes.py_object(_Runaway))
        th.join(timeout)
    assert "value" in box or "error" in box, \
        f"{what} did not return within {timeout:g} s"
    if isinstance(box.get("error"), _Runaway):
        raise AssertionError(f"{what} did not return within {timeout:g} s")
    if "error" in box:
        raise box["error"]
    return box["value"]


# ------------------------------------------------------------ the fixture

class TestTheWorkedCases:
    """Spec 1.5's four worked cases, a branched lane, a mid-lane pass wire and
    a flow cycle with no way in, each graded on its owners, its lane, its tail,
    its loop and its compile.

    Mutant "owner is any upstream TARGET" (the doctor's set walk: collect every
    node upstream along flow wires, through any type, and return the nearest
    TARGET or POOL) failed all three on dome-ends-the-lane, and only there:
        AssertionError: dome-ends-the-lane: ha
        assert 't' == None
        AssertionError: dome-ends-the-lane: t
        {'lane': ['cy', 'ha']} != {'lane': ['cy']}
        {'tail': 'ha'} != {'tail': 'cy'}
        AssertionError: dome-ends-the-lane
        assert {'t': [['cy', 'ha']]} == {'t': [['cy']]}

    The same three tests caught these, one line of each failure quoted:
        "no seen-set" [flow-cycle-with-no-way-in]:
            AssertionError: owner_of('a') did not return within 5 s
            AssertionError: the lane of 't' did not return within 5 s
        "legacy rule in mosaic graphs" [second-target-owns-the-capture]:
            {'m31': [['cy', 'ha']]} != {'m31': [['cy']]}
        "the tail is the deepest stage, branched or not" [branched-lane]:
            {'tail': 'ha'} != {'tail': None}
        "any pass wire from the lane into next" [mid-lane-pass-wire]:
            {'loop': True} != {'loop': False}
        "wire kinds ignored" [af-guide-cycle]:
            {'next': ['t', 'r']} != {'next': ['r']}
        "any node can be walked from" [af-guide-cycle]:
            {'tail': 'r'} != {'tail': 'cy'}
        "no scope notes" [second-target-owns-the-capture]:
            assert [] == ['ha']
        "a note for every scoped stage" [af-guide-cycle]:
            assert ['cy'] == []
    """

    @pytest.mark.parametrize("case", CASES, ids=lambda c: c["id"])
    def test_owner_of_every_lane_node(self, case):
        g = _graph(case)
        for nid, want in case["owners"].items():
            got = _bounded(lambda: _id(owner_of(g, nid)), f"owner_of({nid!r})")
            assert got == want, f"{case['id']}: {nid}"

    @pytest.mark.parametrize("case", CASES, ids=lambda c: c["id"])
    def test_the_lane_its_tail_and_its_loop(self, case):
        g = _graph(case)
        for oid, want in case["lanes"].items():
            owner = g.node(oid)
            got = _bounded(lambda: {
                "lane": [n.id for n in panel_lane(g, owner)],
                "tail": _id(lane_tail(g, owner)),
                "branched": lane_branched(g, owner),
                "loop": bool(loop_wires(g, owner)),
                "next": [n.id for n in lane_next(g, owner)],
            }, f"the lane of {oid!r}")
            assert got == want, f"{case['id']}: {oid}"

    @pytest.mark.parametrize("case", CASES, ids=lambda c: c["id"])
    def test_the_compile_scopes_every_stage(self, case):
        plan = _bounded(lambda: compile_plan(_graph(case), "n"), "compile_plan")
        want = {oid: [ids] for oid, ids in case["compile"]["steps"].items()}
        assert _steps_by_block(plan) == want, case["id"]
        assert [x["node_id"] for x in plan.get("notes", [])] == \
            case["compile"]["notes"], case["id"]

    def test_the_fixture_holds_the_cases_the_spec_names(self):
        """S3-U grades its mirror against this file, so a case quietly dropped
        here is a case dropped from both languages.

        Mutant of the FIXTURE (a scratch copy) "drop branched-lane" failed:
            AssertionError: assert {'af-guide-cy...-the-capture'} >=
            {'af-guide-cy...-the-capture'}
              Extra items in the right set:
              'branched-lane'
        """
        assert {c["id"] for c in CASES} >= {
            "af-guide-cycle", "cycle-then-capture",
            "second-target-owns-the-capture", "dome-ends-the-lane",
            "branched-lane", "mid-lane-pass-wire"}


# ------------------------------------------------------------- owner_of

class TestOwnerOfIsAChainWalk:

    def test_the_capture_after_the_dome_belongs_to_no_target(self):
        """TARGET -> CYCLE -> DOME -> CAPTURE. DOME ends the lane, so the
        CAPTURE belongs to nobody and must compile to nothing (M13 makes that
        loud). The doctor's set walk would find the TARGET upstream and hand
        the CAPTURE to all six panels, which is the leak this rule closes.

        Mutant "owner is any upstream TARGET" failed:
            AssertionError: assert 't' is None
        Mutant "legacy rule in mosaic graphs" failed:
            AssertionError: assert ['cy', 'ha'] == ['cy']
        """
        g = _graph(_case("dome-ends-the-lane"))
        assert _id(owner_of(g, "ha")) is None
        m31 = compile_plan(g, "n")["targets"][0]
        assert [s["node_id"] for s in m31["steps"]] == ["cy"]

    def test_a_legacy_slew_is_part_of_the_lane(self):
        """Every saved flow and every Example still draws SLEW + CENTER between
        the TARGET and its stages (it is legacy, not deleted, spec 1.7). If it
        ended the lane, every one of those stages would belong to no target.

        Mutant "SLEW is not a lane node" failed:
            AssertionError: assert None == 't'
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2), _n("s", "slew", x=100),
                   _n("af", "autofocus", x=200), _n("g", "guide", x=300),
                   _n("c", "capture", x=400)],
            edges=[_e("t", "target", "s", "run"), _e("s", "centered", "af", "run"),
                   _e("af", "focused", "g", "run"), _e("g", "guiding", "c", "run")])
        assert _id(owner_of(g, "c")) == "t"

    def test_a_flow_cycle_does_not_hang_the_walk(self):
        """Two stages feed each other and nothing feeds them. Each has exactly
        one flow parent, so a walk with no memory of where it has been goes
        round for ever. Run in a thread and bounded, so the mutant FAILS
        rather than hanging the suite.

        Mutant "no seen-set" failed (the walk never returned):
            AssertionError: owner_of on a flow cycle did not return within 5 s
        """
        g = _graph(_case("flow-cycle-with-no-way-in"))
        got = _bounded(lambda: {"a": _id(owner_of(g, "a")),
                                "b": _id(owner_of(g, "b")),
                                "tail": _id(lane_tail(g, g.node("t")))},
                       "owner_of on a flow cycle")
        assert got == {"a": None, "b": None, "tail": None}

    def test_two_flow_parents_have_no_owner(self):
        """Only a graph built outside the editor has two wires into one flow
        input (validation refuses it), but the compile routes still compile
        half-built graphs. Two parents are two answers; picking one would hand
        the stage to a block by edge order, so there is no owner.

        Mutant "the first parent wins" failed, and so did "owner is any
        upstream TARGET":
            AssertionError: assert 'a' is None
        """
        g = FlowGraph(
            nodes=[_n("a", "target", rows=3, cols=2), _n("b", "target", y=100),
                   _n("c", "capture", x=200)],
            edges=[_e("a", "target", "c", "run"), _e("b", "target", "c", "run")])
        assert _id(owner_of(g, "c")) is None

    def test_the_same_parent_wired_twice_is_still_one_chain(self):
        """Control for the rule above: a duplicated wire from ONE parent names
        one block, so the owner is not ambiguous.

        Mutant "a parent wired twice is two parents" failed:
            AssertionError: assert None == 'a'
        """
        g = FlowGraph(
            nodes=[_n("a", "target", rows=3, cols=2), _n("c", "capture", x=200)],
            edges=[_e("a", "target", "c", "run", "w1"),
                   _e("a", "target", "c", "run", "w2")])
        assert _id(owner_of(g, "c")) == "a"

    def test_a_node_that_ends_the_lane_is_owned_by_nobody(self):
        """DOME, REPORT and a second TARGET are not lane nodes; asking who
        owns one is asking who owns a node outside every lane. Controls: none
        of them may be answered with the block above them.

        Mutant "any node can be walked from" failed:
            AssertionError: assert FlowNode(id='t', type='target', x=0.0,
            y=0.0, params={'name': 'M31', 'rows': 3, 'cols': 2}) is None
        """
        g = _graph(_case("dome-ends-the-lane"))
        assert owner_of(g, "dm") is None
        g3 = _graph(_case("second-target-owns-the-capture"))
        assert owner_of(g3, "m33") is None
        g1 = _graph(_case("af-guide-cycle"))
        assert owner_of(g1, "r") is None
        assert owner_of(g1, "no-such-node") is None

    def test_a_stage_under_a_pool_belongs_to_the_pool(self):
        """Mutant "POOL is not an owner" failed:
            AssertionError: assert None == 'p'
        """
        g = FlowGraph(
            nodes=[_n("p", "pool", members="A, B"), _n("g", "guide", x=100),
                   _n("c", "capture", x=200)],
            edges=[_e("p", "target", "g", "run"), _e("g", "guiding", "c", "run")])
        assert _id(owner_of(g, "c")) == "p"

    def test_the_loop_wire_is_not_a_step_of_the_cursor(self):
        """The loop wire points backwards from the tail into the TARGET. It is
        an event ("whenever a pass is done"), so reading it as a flow wire
        would make the TARGET a child of its own tail and list it as what
        runs after the mosaic.

        Mutant "wire kinds ignored" (every wire is a flow wire) failed:
            AssertionError: assert ['t', 'r'] == ['r']
        """
        g = _graph(_case("af-guide-cycle"))
        assert [n.id for n in lane_next(g, g.node("t"))] == ["r"]
        assert _id(owner_of(g, "cy")) == "t"

    def test_a_flow_output_dropped_on_next_is_not_a_step(self):
        """FILTER CYCLE 'all done' dropped on TARGET 'next panel' crosses the
        flow/event boundary, which validation refuses and a half-built graph
        can still hold. Read by its source port alone it would be a flow step
        into the TARGET, and the TARGET would run after its own lane.

        Mutant "a wire is a flow wire by its source port alone" failed:
            AssertionError: assert ['t'] == []
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2), _n("cy", "cycle", x=200)],
            edges=[_e("t", "target", "cy", "run"),
                   _e("cy", "complete", "t", "next")])
        assert [n.id for n in lane_next(g, g.node("t"))] == []
        assert _id(owner_of(g, "cy")) == "t"


# ---------------------------------------------------------- the lane shape

class TestTheLaneShape:

    def test_a_branched_lane_has_no_tail(self):
        """AF feeds both CYCLE and CAPTURE Ha: two last stages. Choosing one
        would put the loop wire on a stage the operator did not mean (M12).

        Mutant "the tail is the deepest stage, branched or not" failed:
            AssertionError: assert 'ha' is None
        """
        g = _graph(_case("branched-lane"))
        t = g.node("t")
        assert lane_branched(g, t) is True
        assert _id(lane_tail(g, t)) is None

    def test_fan_out_from_the_target_itself_is_a_branch(self):
        """Spec 1.5 item 4: "no fan-out from the TARGET or between lane nodes".

        Mutant "the tail is the deepest stage, branched or not" failed:
            AssertionError: assert FlowNode(id='c', type='capture', x=200.0,
            y=100.0, params={}) is None
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2),
                   _n("cy", "cycle", x=200), _n("c", "capture", x=200, y=100)],
            edges=[_e("t", "target", "cy", "run"), _e("t", "target", "c", "run")])
        assert lane_branched(g, g.node("t")) is True
        assert lane_tail(g, g.node("t")) is None

    def test_a_non_lane_sibling_is_not_a_branch(self):
        """Control: TARGET feeds a CYCLE and a DOME. DOME is not a lane node,
        so the lane is still one chain and its tail is the CYCLE.

        Mutant "any node can be walked from" (DOME joins the lane) failed:
            AssertionError: assert True is False
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2),
                   _n("cy", "cycle", x=200), _n("dm", "dome", x=200, y=100)],
            edges=[_e("t", "target", "cy", "run"), _e("t", "target", "dm", "run")])
        assert lane_branched(g, g.node("t")) is False
        assert _id(lane_tail(g, g.node("t"))) == "cy"

    def test_an_empty_lane(self):
        """A TARGET wired straight to a REPORT owns nothing: no tail, no loop,
        and nothing to call branched.

        Mutant "any node can be walked from" failed:
            AssertionError: assert ([FlowNode(id=...0, params={})] == []
              Left contains one more item: FlowNode(id='r', type='report',
              x=100.0, y=0.0, params={})
        """
        g = FlowGraph(nodes=[_n("t", "target", rows=3, cols=2), _n("r", "report", x=100)],
                      edges=[_e("t", "target", "r", "session")])
        t = g.node("t")
        assert panel_lane(g, t) == [] and lane_tail(g, t) is None
        assert lane_branched(g, t) is False and loop_wires(g, t) == []

    def test_what_runs_next_names_each_node_once_in_canvas_order(self):
        """The tail's 'all done' wired twice to one REPORT (a duplicate a
        half-built graph can hold) is still one thing that runs next, and two
        different next nodes read in canvas order, as the compile walks them.

        Mutant "lane_next keeps duplicate wires" failed:
            AssertionError: assert ['dm', 'r', 'r'] == ['dm', 'r']
              Left contains one more item: 'r'
        Mutant "lane_next in wire order" failed:
            AssertionError: assert ['r', 'dm'] == ['dm', 'r']
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2), _n("cy", "cycle", x=200),
                   _n("r", "report", x=600), _n("dm", "dome", x=400, y=200)],
            edges=[_e("t", "target", "cy", "run"),
                   _e("cy", "complete", "r", "session", "w1"),
                   _e("cy", "complete", "r", "session", "w2"),
                   _e("cy", "complete", "dm", "run", "w3")])
        assert [n.id for n in lane_next(g, g.node("t"))] == ["dm", "r"]


# ------------------------------------------------------------ the loop wire

class TestTheLoopWire:

    def test_the_loop_is_the_pass_wire_from_the_tail_into_next(self):
        """Mutant "any node can be walked from" (REPORT becomes the tail)
        failed:
            AssertionError: assert [] == ['loop']
        """
        g = _graph(_case("af-guide-cycle"))
        assert [e.id for e in loop_wires(g, g.node("t"))] == ["loop"]

    def test_a_pass_wire_from_a_mid_lane_stage_is_not_the_loop(self):
        """CAPTURE Ha comes after the CYCLE the wire leaves, so the loop would
        rotate panels before CAPTURE Ha was ever shot on them (M12).

        Mutant "any pass wire from the lane into next" failed:
            AssertionError: assert ['early'] == []
        """
        g = _graph(_case("mid-lane-pass-wire"))
        assert [e.id for e in loop_wires(g, g.node("t"))] == []

    def test_a_pass_wire_into_another_block_is_nobodys_loop(self):
        """The CYCLE is M31's tail, but its pass wire goes into M33's next.
        It closes neither circle (M4: "this wire does nothing").

        Mutant "loop wire into any block's next" failed:
            AssertionError: assert [FlowEdge(id=...oPort='next')] == []
              Left contains one more item: FlowEdge(id='stray', from_='cy',
              fromPort='pass', to='m33', toPort='next')
        """
        c = _case("second-target-owns-the-capture")
        g = _graph(c).model_copy(update={"edges": [
            *[e for e in _graph(c).edges if e.id != "loop"],
            _e("cy", "pass", "m33", "next", "stray")]})
        assert loop_wires(g, g.node("m31")) == []
        assert loop_wires(g, g.node("m33")) == []

    @pytest.mark.parametrize("from_port,to_port", [
        ("frame", "next"),      # the graded-frame event, not the pass
        ("pass", "arm"),        # into the flow input, not next
    ])
    def test_the_ports_are_part_of_the_loop(self, from_port, to_port):
        """Controls: the wire must leave ``pass`` and enter ``next``.

        Mutant "loop wire from any port of the tail" failed [frame-next]:
            Left contains one more item: FlowEdge(id='2233723b9f6e',
            from_='cy', fromPort='frame', to='t', toPort='next')
        Mutant "loop wire into any port of the block" failed [pass-arm]:
            Left contains one more item: FlowEdge(id='e1cdeeb59671',
            from_='cy', fromPort='pass', to='t', toPort='arm')
        """
        g = FlowGraph(
            nodes=[_n("t", "target", rows=3, cols=2), _n("cy", "cycle", x=200)],
            edges=[_e("t", "target", "cy", "run"),
                   _e("cy", from_port, "t", to_port)])
        assert loop_wires(g, g.node("t")) == []


# ------------------------------------------------------- scoping in compile

class TestScopingInTheCompile:

    def test_the_capture_after_a_second_target_stays_off_the_mosaic(self):
        """Worked case 3. Under the canvas-order rule the CAPTURE after
        TARGET(M33) is appended to every target seen so far, M31 included, so
        six M31 panels would each owe it.

        Mutant "legacy rule in mosaic graphs" failed:
            AssertionError: assert ['cy', 'ha'] == ['cy']
        """
        plan = compile_plan(_graph(_case("second-target-owns-the-capture")), "n")
        by = {t["node_id"]: [s["node_id"] for s in t["steps"]] for t in plan["targets"]}
        assert by["m31"] == ["cy"]
        assert by["m33"] == ["ha"]

    def test_a_two_lane_flow_with_a_mosaic_scopes_by_wire(self):
        """Two separate lanes, laid out so canvas order interleaves them: the
        mosaic's TARGET, the single TARGET, then each one's stage. By canvas
        order both stages would reach both targets.

        Mutant "legacy rule in mosaic graphs" failed:
            AssertionError: assert {'a': [['cy',...[['cy', 'c']]} ==
            {'a': [['cy']], 'b': [['c']]}
              {'a': [['cy', 'c']]} != {'a': [['cy']]}
              {'b': [['cy', 'c']]} != {'b': [['c']]}
        """
        g = FlowGraph(
            nodes=[_n("a", "target", x=100, name="M31", rows=2, cols=2),
                   _n("b", "target", x=200, y=300, name="M33"),
                   _n("cy", "cycle", x=300, plan="L 60, R 60"),
                   _n("c", "capture", x=400, y=300, filter="Ha", count=10)],
            edges=[_e("a", "target", "cy", "run"), _e("b", "target", "c", "run"),
                   _e("cy", "pass", "a", "next")])
        assert _steps_by_block(compile_plan(g, "n")) == {
            "a": [["cy"]], "b": [["c"]]}

    def test_every_pool_member_gets_its_own_lanes_stage_only(self):
        """A POOL lane beside a mosaic: both members carry the pool's CAPTURE,
        in their own dicts, and none of the mosaic's CYCLE.

        Mutant "legacy rule in mosaic graphs" failed:
            {'t': [['cy', 'c']]} != {'t': [['cy']]}
            {'p': [['cy', 'c'], ['cy', 'c']]} != {'p': [['c'], ['c']]}
        Mutant "POOL is not an owner" failed:
            AssertionError: assert {'p': [[], []], 't': [['cy']]} ==
            {'p': [['c'],...'t': [['cy']]}
        """
        g = FlowGraph(
            nodes=[_n("t", "target", x=0, name="M31", rows=3, cols=2),
                   _n("p", "pool", x=100, y=300, members="A, B"),
                   _n("cy", "cycle", x=200, plan="L 60"),
                   _n("c", "capture", x=300, y=300, count=5)],
            edges=[_e("t", "target", "cy", "run"), _e("p", "target", "c", "run")])
        plan = compile_plan(g, "n")
        assert _steps_by_block(plan) == {"t": [["cy"]], "p": [["c"], ["c"]]}
        a, b = [t for t in plan["targets"] if t["node_id"] == "p"]
        a["steps"][0]["count"] = 999
        assert b["steps"][0]["count"] == 5

    def test_with_no_multi_panel_block_wire_scoping_still_applies(self):
        """Worked case 3's graph with M31 made 1x1.

        RE-PINNED (W2 integration, backlog WP-19(a), #151, owner-approved
        2026-09-30): this case used to pin the OLD, narrower trigger --
        canvas order stayed in force for a graph with no multi-panel block,
        leak and all (I-05: the CAPTURE after M33 also reached M31). #151's
        own general case is exactly this leak with no mosaic involved at
        all: two independent TARGETs, each with its own lane, where what a
        stage shoots should depend on its wires, not where its card sits.
        ``needs_wire_scoping`` now turns on for ANY graph with more than one
        TARGET/POOL block (`len(owners) > 1`), not only a multi-panel one,
        so this graph -- two TARGETs, M31 and M33, whatever M31's panel
        count -- now scopes by wire exactly as the unmodified 3x2 case
        above does: ``cy`` belongs to M31 alone (its own wire), ``ha`` to
        M33 alone, and the compile notes that the CAPTURE would have
        reached M31 too under canvas order. The old assertions
        (``by["m31"] == ["cy", "ha"]``, no notes) described the leak this
        WP was built to close; the new ones describe the fix.

        Mutant "the wire rule only with a mosaic" (``needs_wire_scoping``
        reverted to ``any(is_multi_panel(n) for n in owners)``), observed:
            AssertionError: assert ['cy', 'ha'] == ['cy']
        """
        c = _case("second-target-owns-the-capture")
        nodes = [n if n["id"] != "m31" else {**n, "params": {"name": "M31"}}
                 for n in c["graph"]["nodes"]]
        g = FlowGraph.model_validate({**c["graph"], "nodes": nodes})
        plan = compile_plan(g, "n")
        by = {t["node_id"]: [s["node_id"] for s in t["steps"]] for t in plan["targets"]}
        assert by["m31"] == ["cy"]
        assert by["m33"] == ["ha"]
        notes = plan.get("notes") or []
        assert any(n.get("node_id") == "ha" for n in notes), (
            f"the scope note for the CAPTURE that canvas order would also "
            f"have given M31 is missing: {notes}")

    @pytest.mark.parametrize("rows,cols,multi", [
        (None, None, False),        # absent means 1, which is every saved flow
        (1, 1, False),
        (3, 1, True),
        (1, 3, True),               # a single row of three is still a mosaic
        ("2", "2", True),           # the inspector may hand a number as text
        ("abc", 4, True),           # unreadable reads as 1, the other still counts
        ("abc", "", False),
        (0, 5, True),               # 0 is not a grid size; it reads as 1
        (-3, -3, False),
        (1.9, 1, False),            # a grid is whole panels: 1.9 rows is 1
        (float("nan"), 2, True),
        (float("inf"), 1, False),
        (True, 1, False),
    ])
    def test_rows_and_cols_are_read_defensively(self, rows, cols, multi):
        """Spec 3.1: missing rows and cols mean 1, the old meaning. Anything
        that is not a whole number of at least 1 reads as 1, so a hand-edited
        file cannot switch a graph's scoping rule with a string.

        Mutant "rows only" (cols ignored) failed four cases, each with
            AssertionError: assert False is True
        on [1-3-True], [abc-4-True], [0-5-True] and [nan-2-True].
        """
        params = {k: v for k, v in (("rows", rows), ("cols", cols)) if v is not None}
        assert is_multi_panel(_n("t", "target", **params)) is multi

    def test_only_a_target_is_a_mosaic(self):
        """A POOL has no grid; rows and cols on one (a hand-edited file) must
        not flip the whole graph to the wire rule. Control.

        Mutant "any node type can be a mosaic" failed:
            AssertionError: assert True is False
        """
        assert is_multi_panel(_n("p", "pool", rows=3, cols=2)) is False


class TestTheCompileSaysWhenTheRulesDiffer:

    def test_a_narrowed_stage_is_named(self):
        """Mutant "no scope notes" failed:
            KeyError: 'notes'
        """
        plan = compile_plan(_graph(_case("second-target-owns-the-capture")), "n")
        (note,) = plan["notes"]
        assert note["node_id"] == "ha" and note["level"] == "note"
        assert "CAPTURE LOOP Ha" in note["text"]
        assert "TARGET M33" in note["text"] and "M31" in note["text"]

    def test_an_unowned_stage_is_named_louder(self):
        """It compiles to nothing, which the canvas-order rule never did.

        Mutant "no scope notes" failed:
            KeyError: 'notes'
        Mutant "every scope note is a note" failed:
            AssertionError: assert ('ha' == 'ha'
                ha and 'note' == 'warn'
        """
        plan = compile_plan(_graph(_case("dome-ends-the-lane")), "n")
        (note,) = plan["notes"]
        assert note["node_id"] == "ha" and note["level"] == "warn"
        assert "CAPTURE LOOP Ha belongs to no TARGET" in note["text"]
        assert "M31" in note["text"]

    def test_a_note_names_each_target_once(self):
        """Two single TARGETs that share a name are two blocks but one word
        to the operator; the note lists the names canvas order would have
        used, each once.

        Mutant "entry names not deduplicated" failed:
            AssertionError: assert 'would have been shot on M31, M33.' in
            'CAPTURE LOOP Ha belongs to no TARGET, ... By canvas order it
            would have been shot on M31, M33, M33. Give it a TARGET.'
        """
        c = _case("dome-ends-the-lane")
        g = FlowGraph.model_validate({**c["graph"], "nodes": [
            *c["graph"]["nodes"],
            # right of the CYCLE and left of the CAPTURE in canvas order, so
            # only the CAPTURE is one canvas order would have given them
            {"id": "b", "type": "target", "x": 300, "y": 300,
             "params": {"name": "M33"}},
            {"id": "b2", "type": "target", "x": 350, "y": 300,
             "params": {"name": "M33"}}]})
        (note,) = compile_plan(g, "n")["notes"]
        assert note["node_id"] == "ha"
        assert "would have been shot on M31, M33." in note["text"]

    def test_a_stage_both_rules_agree_on_is_not_mentioned(self):
        """Control: in worked case 1 the CYCLE goes to M31 by either rule, so
        there is no key at all (absent, never an empty list, as ``campaign``).

        Mutant "a note for every scoped stage" failed, and so did "an empty
        notes list on every compile":
            AssertionError: assert 'notes' not in {'automation': {},
            'instructions': [{'action': 'target', 'to_port': 'next', 'when':
            'cycle.pass'}], 'name': 'n', 'note...
        """
        plan = compile_plan(_graph(_case("af-guide-cycle")), "n")
        assert "notes" not in plan


# ------------------------------------------------ placing the loop wire

def _loop_case(case_id: str) -> dict:
    found = [c for c in LOOP_CASES if c["id"] == case_id]
    assert found, f"the fixture no longer carries loop case {case_id}"
    return found[0]


def _wire(e: FlowEdge) -> dict:
    """A wire in the fixture's own shape, so a mismatch prints both ends."""
    return {"id": e.id, "from": e.from_, "fromPort": e.fromPort,
            "to": e.to, "toPort": e.toPort}


class TestTheLoopCases:
    """The graphs the editor makes when it places or lifts a block's loop
    wire (#189 S4; spec 1.4 "When the wire is added", 2.5 DONE), graded by
    the rules the server runs them under.

    The editor's rule (ui panelLane.ts ``withLoop``) has no Python twin: the
    server only READS the wire. So the fixture records what the TypeScript
    makes, panelLane.test.ts holds the TypeScript to it, and this class holds
    the fixture to compile.py: the result is a graph validation takes, its
    loop wire is the one ``loop_wires`` finds and no other, and
    ``lane_refusals`` (M12, M13) has nothing to say. A result recorded from a
    wrong rule fails here, and a rule that drifts from the recorded result
    fails there.

    Mutant of the FIXTURE (a scratch copy) "loop-on recorded from the first
    owned stage" (the ``loop`` wire's ``from`` in loop-on's result and in its
    ``loop_wire`` set to ``cy``: the graph the TypeScript mutant "loop from
    the first owned stage" makes) failed two of these tests on loop-on:
        FAILED ...::test_loop_wires_finds_exactly_the_recorded_wire[loop-on]
            AssertionError: loop-on
            assert [] == [{'from': 'cy...o': 't', ...}]
              Right contains one more item: {'from': 'cy', 'fromPort':
              'pass', 'id': 'loop', 'to': 't', ...}
        FAILED ...::test_the_result_has_no_lane_refusal[loop-on]
            AssertionError: loop-on
            assert [{'code': 'M1...of its own.'}] == []
              Left contains one more item: {'code': 'M12', 'node_id': 'cy',
              'text': 'the loop wire starts at FILTER CYCLE, but CAPTURE LOOP
              Ha comes after it in ...rt the loop wire at CAPTURE LOOP Ha to
              shoot every stage on every panel, or give CAPTURE LOOP Ha a
              TARGET of its own.'}
    (2 failed, 73 passed.) The same fixture mutant fails panelLane.test.ts's
    loop-on case, so neither language accepts a wire from the first stage.
    """

    @pytest.mark.parametrize("case", LOOP_CASES, ids=lambda c: c["id"])
    def test_the_result_is_a_graph_the_server_takes(self, case):
        assert FlowGraph.model_validate(case["result"]).validation_errors() == []

    @pytest.mark.parametrize("case", LOOP_CASES, ids=lambda c: c["id"])
    def test_loop_wires_finds_exactly_the_recorded_wire(self, case):
        g = FlowGraph.model_validate(case["result"])
        want = [] if case["loop_wire"] is None else [case["loop_wire"]]
        assert [_wire(e) for e in loop_wires(g, case["block"])] == want, case["id"]

    @pytest.mark.parametrize("case", LOOP_CASES, ids=lambda c: c["id"])
    def test_the_result_has_no_lane_refusal(self, case):
        assert lane_refusals(FlowGraph.model_validate(case["result"])) == [], case["id"]

    def test_the_fixture_holds_the_named_cases(self):
        """The TypeScript grades itself against these ids too.

        Mutant of the FIXTURE (a scratch copy) "loop-off renamed" failed:
            AssertionError: assert {'loop-off-re...ingle-target'} >=
            {'loop-off', ...ingle-target'}
              Extra items in the right set:
              'loop-off'
        and test_loop_off_lifts_a_wire_the_server_refuses with it:
            AssertionError: the fixture no longer carries loop case loop-off
        """
        assert {c["id"] for c in LOOP_CASES} >= {
            "loop-on", "loop-off", "loop-on-single-target"}

    def test_loop_on_tells_the_tail_from_the_first_stage(self):
        """The loop-on case is only a test of "the wire leaves the TAIL" while
        the lane's first stage is not its tail and would make a wire the
        server refuses. Premises, so an edit that shrinks the lane to one
        stage cannot leave the case unable to tell the two rules apart:
        before DONE the block has no loop wire, and the same wire drawn from
        the lane's first stage is M12.

        Mutant of the FIXTURE (a scratch copy) "loop-on's lane is one stage"
        (the CAPTURE and its two wires deleted from graph and result, the
        CYCLE wired to the REPORT and the loop wire drawn from the CYCLE)
        failed:
            AssertionError: loop-on's lane starts at its tail, cy: the wire
            from the first stage IS the loop wire, so the case cannot tell
            the rules apart
        (1 failed, 74 passed), while panelLane.test.ts stayed green on it
        (22/22): only this premise sees a case that has stopped testing the
        rule.
        """
        case = _loop_case("loop-on")
        before = FlowGraph.model_validate(case["graph"])
        assert loop_wires(before, "t") == []
        first = panel_lane(before, "t")[0]
        assert first.id != _id(lane_tail(before, "t")), (
            f"loop-on's lane starts at its tail, {first.id}: the wire from the "
            f"first stage IS the loop wire, so the case cannot tell the rules apart")
        wrong = FlowGraph.model_validate({**case["result"], "edges": [
            {**e, "from": first.id} if e["id"] == case["loop_wire"]["id"] else e
            for e in case["result"]["edges"]]})
        assert [(r["code"], r["node_id"]) for r in lane_refusals(wrong)] == \
            [("M12", first.id)]

    def test_loop_off_lifts_a_wire_the_server_refuses(self):
        """Premise of loop-off: its stale pass wire from mid-lane is M12
        before the loop is turned off, so a result that kept it would fail
        ``test_the_result_has_no_lane_refusal``. The M33 mosaic's own loop is
        the control: it is M33's loop wire before and after.

        Mutant of the FIXTURE (a scratch copy) "loop-off keeps the stale
        wire" (``stale`` left in loop-off's result) failed:
            FAILED ...::test_the_result_has_no_lane_refusal[loop-off]
            AssertionError: loop-off
            assert [{'code': 'M1...of its own.'}] == []
              Left contains one more item: {'code': 'M12', 'node_id': 'cy',
              'text': 'the loop wire starts at FILTER CYCLE, but CAPTURE LOOP
              Ha comes after it in ...rt the loop wire at CAPTURE LOOP Ha to
              shoot every stage on every panel, or give CAPTURE LOOP Ha a
              TARGET of its own.'}
        (1 failed, 74 passed), and panelLane.test.ts's loop-off case with it.
        """
        case = _loop_case("loop-off")
        before = FlowGraph.model_validate(case["graph"])
        assert [(r["code"], r["node_id"]) for r in lane_refusals(before)] == \
            [("M12", "cy")]
        after = FlowGraph.model_validate(case["result"])
        assert [e.id for e in loop_wires(before, "m33")] == ["m33-loop"]
        assert [e.id for e in loop_wires(after, "m33")] == ["m33-loop"]


# ------------------------------------ a stranded loop, and what rotates (#410)

#: The loop cases whose press MOVES a pass wire the lane already has (#410),
#: and the control whose stray wire it must leave alone.
LOOP_STRANDED = ("loop-on-stranded", "loop-on-stranded-twice",
                 "loop-on-stranded-beside-the-tail-loop")
LOOP_FOREIGN = "loop-on-foreign-pass-wire-control"


def _rotates(g: FlowGraph, block_id: str) -> bool:
    """Whether the run rotates the block's panels, by compile.py's rules: a
    multi-panel block, a loop wire (``loop_wires``) and no M12 on its lane
    (``lane_refusals``, which ``to_plan`` raises on). The compile's own
    entry reads ``loop`` from ``loop_wires`` alone, so a tail wire beside a
    stale mid-lane one is ``loop`` True in a graph the run refuses; the card
    must say what the RUN does, which is this."""
    g = g.with_defaults()
    block = next(n for n in g.nodes if n.id == block_id)
    lane = {n.id for n in panel_lane(g, block_id)}
    m12 = [r for r in lane_refusals(g) if r["code"] == "M12"
           and (r["node_id"] == block_id or r["node_id"] in lane)]
    return is_multi_panel(block) and bool(loop_wires(g, block_id)) and not m12


def _into_next(e: dict, block: str) -> bool:
    return e["fromPort"] == "pass" and e["to"] == block and e["toPort"] == "next"


class TestAStrandedLoop:
    """LOOP PANELS, and the modal's RUN toggle, on a lane whose loop wire is
    stranded mid-lane (#410; spec 1.5 item 6: a flow saved before S4 opens
    that way). ``withLoop(..., true)`` used to add a second pass wire from
    the tail and leave the stranded one, so the flow stayed M12 while the
    card read "rotate" and the arc carried "every pass: next panel". It now
    MOVES the stranded wire to the tail, keeping its id and its place, as
    ``carryLoopWire`` does on an append.

    The fixture's stranded cases are graded by TestTheLoopCases like every
    loop case (a valid graph, the recorded loop wire, no lane refusal).
    This class holds their premises, so a case cannot pass by having
    stopped testing the rule, and the ``rotates`` column every loop case
    carries, which panelLane.test.ts holds ``targetLoops`` to.

    Named mutants, each run in the private scratch copy
    scratchpad/S5-LOOP-mut (#254); see the tests below for what each turned
    red. The TypeScript mutant "withLoop adds a second wire" (panelLane.ts
    withLoop's `true` branch put back as it was: nothing lifted, a new wire
    added from the tail whenever the tail has none) failed the three stranded
    cases in panelLane.test.ts (44/47), loop-on-stranded as
        withLoop made ["e1:t.target->cy.run","loop:cy.pass->t.next",
        "e2:cy.complete->af.run","e3:af.focused->r.session",
        "loop:af.pass->t.next"], the fixture the server grades records
        ["e1:t.target->cy.run","loop:af.pass->t.next",
        "e2:cy.complete->af.run","e3:af.focused->r.session"]
    and the graph it makes is the one
    ``test_a_second_wire_leaves_the_flow_refused`` hands to compile.py.
    """

    @pytest.mark.parametrize("case", LOOP_CASES, ids=lambda c: c["id"])
    def test_rotates_is_what_compile_py_says(self, case):
        """What the card footer and the loop chip say (``targetLoops``) is
        recorded per case, before and after, and held here to compile.py.

        Mutant of the FIXTURE (a scratch copy) "the tail-loop case recorded
        as rotating before the press" (its ``rotates.graph`` true, which is
        what ``loop_wires`` alone would say) failed:
            FAILED tests/test_flows_panel_lane.py::TestAStrandedLoop::test_rotates_is_what_compile_py_says[loop-on-stranded-beside-the-tail-loop]
            AssertionError: loop-on-stranded-beside-the-tail-loop: rotates
            recorded {'graph': True, 'result': True}, compile.py says
            {'graph': False, 'result': True}
        (1 failed, 142 passed), and panelLane.test.ts (46/47) against it:
            x targetLoops on loop case loop-on-stranded-beside-the-tail-loop,
            before and after, is what compile.py says: targetLoops answered
            {"graph":false,"result":true}, the fixture the server grades
            records {"graph":true,"result":true}
        """
        got = {k: _rotates(FlowGraph.model_validate(case[k]), case["block"])
               for k in ("graph", "result")}
        assert got == case["rotates"], (
            f"{case['id']}: rotates recorded {case['rotates']}, compile.py "
            f"says {got}")

    def test_the_fixture_holds_the_stranded_cases(self):
        """The TypeScript grades itself against these ids too.

        Mutant of the FIXTURE (a scratch copy) "loop-on-stranded renamed
        away" failed:
            AssertionError: assert {'loop-off', ...renamed', ...} >=
            {'loop-on-for...randed-twice'}
              Extra items in the right set:
              'loop-on-stranded'
        with the three premise tests below on that id ("the fixture no
        longer carries loop case loop-on-stranded"), 4 failed, 139 passed;
        panelLane.test.ts (46/47): "x the loop cases are read from
        panel_lane_cases.json, every column graded: the fixture no longer
        carries loop case loop-on-stranded".
        """
        assert {c["id"] for c in LOOP_CASES} >= {*LOOP_STRANDED, LOOP_FOREIGN}

    @pytest.mark.parametrize("case_id", LOOP_STRANDED)
    def test_before_the_press_the_lane_is_m12_at_each_stranded_wire(self, case_id):
        """Premise of each stranded case: before the press every pass wire
        into the block's ``next`` that leaves a stage of its lane other than
        the tail is M12, and the block does not rotate. A case whose wire
        already left the tail would pass whatever ``withLoop`` did.

        Mutant of the FIXTURE (a scratch copy) "loop-on-stranded already on
        the tail" (its ``loop`` wire drawn from ``af`` in graph and result
        alike) failed:
            AssertionError: loop-on-stranded: no stranded wire before the
            press, so the case cannot tell a move from an add
            assert [] != []
        with test_rotates_is_what_compile_py_says and
        test_a_second_wire_leaves_the_flow_refused on the same case (3
        failed, 140 passed). panelLane.test.ts's ``withLoop`` grade stays
        green on it, a graph that already loops being one ``withLoop``
        rightly leaves alone; only its ``rotates`` grade sees it (46/47):
            x targetLoops on loop case loop-on-stranded, before and after, is
            what compile.py says: targetLoops answered
            {"graph":true,"result":true}, the fixture the server grades
            records {"graph":false,"result":true}
        """
        case = _loop_case(case_id)
        before = FlowGraph.model_validate(case["graph"])
        tail = _id(lane_tail(before, case["block"]))
        lane = {n.id for n in panel_lane(before, case["block"])}
        stranded = sorted({e["from"] for e in case["graph"]["edges"]
                           if _into_next(e, case["block"])
                           and e["from"] in lane and e["from"] != tail})
        assert stranded != [], (
            f"{case_id}: no stranded wire before the press, so the case "
            f"cannot tell a move from an add")
        m12 = sorted(r["node_id"] for r in lane_refusals(before)
                     if r["code"] == "M12")
        assert (m12, _rotates(before, case["block"])) == (stranded, False), case_id

    @pytest.mark.parametrize("case_id", LOOP_STRANDED)
    def test_a_second_wire_leaves_the_flow_refused(self, case_id):
        """#410 as filed: the press adds a wire from the tail beside the
        stranded one(s). compile.py then finds a loop wire (so the card would
        say "rotate", the doctor's M12 notwithstanding) and still refuses the
        flow at the stranded source. This is the graph the TypeScript mutant
        "withLoop adds a second wire" makes (for the tail-loop case, which
        already has its tail wire, that mutant adds nothing and leaves the
        graph as it was, which is also M12): held here so the fixture's
        results cannot be recorded from that rule.

        Red under the FIXTURE mutant "loop-on-stranded already on the tail"
        (see the test above), where the second wire is no longer beside a
        stranded one:
            AssertionError: loop-on-stranded
            assert 0 >= 1
        """
        case = _loop_case(case_id)
        before = case["graph"]
        tail = _id(lane_tail(FlowGraph.model_validate(before), case["block"]))
        has_own = any(_into_next(e, case["block"]) and e["from"] == tail
                      for e in before["edges"])
        second = before["edges"] if has_own else [
            *before["edges"], {"id": "loop", "from": tail, "fromPort": "pass",
                               "to": case["block"], "toPort": "next"}]
        g = FlowGraph.model_validate({**before, "edges": second})
        assert loop_wires(g, case["block"]) != [], case_id
        assert [r["code"] for r in lane_refusals(g)].count("M12") >= 1, case_id
        assert not _rotates(g, case["block"]), case_id

    @pytest.mark.parametrize("case_id", LOOP_STRANDED)
    def test_the_press_moves_or_drops_pass_wires_and_nothing_more(self, case_id):
        """What a press on a stranded lane can make, held here as well as in
        the TypeScript: the graph's wires in their order, where a pass wire
        into the block's ``next`` from a stage of its lane is either kept
        (the tail's own), re-sourced to the tail with its id and its place,
        or gone, and nothing else changes and no wire is added. Exactly one
        pass wire into ``next`` is left.

        Mutant of the FIXTURE (a scratch copy) "loop-on-stranded recorded as
        #410 filed it" (the stranded ``loop`` wire kept on ``cy`` and a new
        ``loop2`` from ``af`` appended to its result, ``loop_wire`` loop2)
        failed this case:
            AssertionError: loop-on-stranded: the result adds a wire, which
            no press on a stranded lane makes: loop2
        with test_the_result_has_no_lane_refusal[loop-on-stranded]
            Left contains one more item: {'code': 'M12', 'node_id': 'cy',
            'text': 'the loop wire starts at FILTER CYCLE, but AUTOFOCUS comes
            after it in the TA...el lane. ...'}
        and test_rotates_is_what_compile_py_says[loop-on-stranded] (rotates
        recorded {'graph': False, 'result': True}, compile.py says {'graph':
        False, 'result': False}): 3 failed, 140 passed. panelLane.test.ts
        failed the case against it too (45/47): "withLoop made
        [...,"loop:af.pass->t.next",...], the fixture the server grades
        records [...,"loop:cy.pass->t.next",...,"loop2:af.pass->t.next"]".
        """
        case = _loop_case(case_id)
        block = case["block"]
        before, after = case["graph"], case["result"]
        assert after["nodes"] == before["nodes"], case_id
        tail = _id(lane_tail(FlowGraph.model_validate(before), block))
        was = {e["id"]: e for e in before["edges"]}
        added = [e["id"] for e in after["edges"] if e["id"] not in was]
        assert added == [], (
            f"{case_id}: the result adds a wire, which no press on a "
            f"stranded lane makes: {', '.join(added)}")
        kept_order = [e["id"] for e in before["edges"]
                      if e["id"] in {a["id"] for a in after["edges"]}]
        assert [e["id"] for e in after["edges"]] == kept_order, case_id
        for now in after["edges"]:
            old = was[now["id"]]
            assert now == old or (_into_next(old, block)
                                  and now == {**old, "from": tail}), (
                f"{case_id}: {old} became {now}, which no press makes")
        gone = [e for e in before["edges"]
                if e["id"] not in {a["id"] for a in after["edges"]}]
        assert all(_into_next(e, block) for e in gone), case_id
        assert [e["id"] for e in after["edges"] if _into_next(e, block)] == \
            [case["loop_wire"]["id"]], case_id

    def test_the_foreign_control_is_one_a_wider_repair_would_break(self):
        """The control holds the other edge of "a stage of the lane", as
        carry-foreign-pass-wire-control does for the carry: the stray wire
        leaves a stage M33 owns, outside M31's lane, so it is M4's warning,
        not M12, and M31 does not rotate on it. Re-sourced to M31's tail, as
        a repair that moved every pass wire into ``next`` would, it would
        become M31's loop, a rotation nobody asked for; left alone, the
        press adds the loop wire beside it and M31 rotates on that.

        Mutant of the FIXTURE (a scratch copy) "the stray wire is the
        block's own" (``stray`` drawn from ``cy`` in graph and result, so it
        leaves M31's tail and is its loop wire already) failed:
            AssertionError: the stray wire leaves cy, a stage of M31's own
            lane, so the control no longer tells the lane from any owned stage
            assert 'cy' not in {'cy'}
        with test_loop_wires_finds_exactly_the_recorded_wire and
        test_rotates_is_what_compile_py_says for this case (3 failed, 140
        passed), and panelLane.test.ts's case and rotates grade (45/47).
        """
        case = _loop_case(LOOP_FOREIGN)
        before = FlowGraph.model_validate(case["graph"])
        stray = next(e for e in before.edges
                     if e.fromPort == "pass" and e.to == case["block"])
        lane = {n.id for n in panel_lane(before, case["block"])}
        assert stray.from_ not in lane, (
            f"the stray wire leaves {stray.from_}, a stage of M31's own "
            f"lane, so the control no longer tells the lane from any owned "
            f"stage")
        owner = owner_of(before, stray.from_)
        assert owner is not None and owner.id != case["block"], stray.from_
        assert lane_refusals(before) == []
        assert not _rotates(before, case["block"])
        tail = _id(lane_tail(before, case["block"]))
        wider = FlowGraph.model_validate({**case["graph"], "edges": [
            {**e, "from": tail} if e["id"] == stray.id else e
            for e in case["graph"]["edges"]]})
        assert [e.id for e in loop_wires(wider, case["block"])] == [stray.id]


# ------------------------------------------------ carrying the loop wire

CARRY_CASES = _FIXTURE_JSON["carry_cases"]

#: The carry cases that MOVE a wire (#331), and the controls that must not.
CARRY_MOVES = ("carry-autofocus-after-looped-cycle",
               "carry-capture-after-autofocus-stranding-the-loop",
               "carry-capture-after-autofocus-holding-the-loop",
               "carry-guide-after-looped-capture")
CARRY_CONTROLS = ("carry-single-target-control", "carry-no-loop-wire-control",
                  "carry-foreign-pass-wire-control")


def _carry_case(case_id: str) -> dict:
    found = [c for c in CARRY_CASES if c["id"] == case_id]
    assert found, f"the fixture no longer carries carry case {case_id}"
    return found[0]


def _uncarried(case: dict) -> FlowGraph:
    """The case's graph with the drawn wire added and nothing carried: what
    the connect wrote for these shapes before #331, the loop left behind."""
    return FlowGraph.model_validate({**case["graph"], "edges": [
        *case["graph"]["edges"], case["connect"]]})


class TestTheCarryCases:
    """The graphs the editor makes when a stage is appended after the tail of
    a lane (#189 S4, #331; spec 1.5 item 6), graded by the rules the server
    runs them under.

    The editor's rule (ui flowsSlice.ts ``carryLoopWire``) has no Python
    twin, as ``withLoop`` has none: the server only READS the wire. So the
    fixture records what the TypeScript makes, panelLane.test.ts and
    flowsSlice.test.ts hold the TypeScript to it, and this class holds the
    fixture to compile.py: the result is a graph validation takes, its tail
    and loop wires are the ones recorded, ``lane_refusals`` (M12, M13) has
    nothing to say, and the result is the connect and a carry, nothing more.

    Case 1 is an AUTOFOCUS appended after a looped FILTER CYCLE, and case 2
    a CAPTURE appended after an AUTOFOCUS that holds the loop or stranded it
    (the flow as S3 left it). Both run only because AUTOFOCUS and GUIDE
    gained a ``pass`` output. Named mutants, each in a private scratch copy
    (#254):

    Mutant of nodes.py "AUTOFOCUS has no pass" (``_e("pass", "pass done")``
    dropped from AUTOFOCUS's outs) failed case 1 here, because its result's
    loop wire leaves a port the vocabulary no longer has:
        FAILED ...::test_the_result_is_a_graph_the_server_takes[carry-autofocus-after-looped-cycle]
            AssertionError: carry-autofocus-after-looped-cycle
            assert ["autofocus h... port 'pass'"] == []
              Left contains one more item: "autofocus has no output port 'pass'"
        (7 failed, 219 passed across this file and test_flows_vocabulary_s3.py,
        whose port, PASS_TYPES and AUTOFOCUS pass-wire cases fail with it;
        the same 7 failed, 225 passed on the re-run of 2026-09-27)
    and panelLane.test.ts and flowsSlice.test.ts failed the same case with
    the same mutant in nodeDefs.ts, where the carry leaves the wire on the
    cycle (M12). The TypeScript mutant "carry only from the pre-connect
    tail" fails case 2's stranding shape there (see panelLane.test.ts);
    this file grades the graph it should have made.

    Mutant of the FIXTURE "case 1 recorded as S3 left it" (a scratch copy:
    the ``loop`` wire in carry-autofocus-after-looped-cycle's result left on
    ``cy``) failed:
        FAILED ...::test_the_tail_and_the_loop_wires_are_the_recorded_ones[carry-autofocus-after-looped-cycle]
            AssertionError: carry-autofocus-after-looped-cycle
            assert ('af', []) == ('af', ['loop'])
        FAILED ...::test_the_result_has_no_lane_refusal[carry-autofocus-after-looped-cycle]
            assert [{'code': 'M1...of its own.'}] == []
              Left contains one more item: {'code': 'M12', 'node_id': 'cy',
              'text': 'the loop wire starts at FILTER CYCLE, but AUTOFOCUS comes
              after it in the TA...el lane. Start the loop wire at AUTOFOCUS to
              shoot every stage on every panel, or give AUTOFOCUS a TARGET of its
              own.'}
        (2 failed, 30 passed of this class), and panelLane.test.ts and
        flowsSlice.test.ts failed their case 1 against it, since the carry
        makes the graph the spec asks for.
    """

    @pytest.mark.parametrize("case", CARRY_CASES, ids=lambda c: c["id"])
    def test_the_result_is_a_graph_the_server_takes(self, case):
        errors = FlowGraph.model_validate(case["result"]).validation_errors()
        assert errors == [], case["id"]

    @pytest.mark.parametrize("case", CARRY_CASES, ids=lambda c: c["id"])
    def test_the_tail_and_the_loop_wires_are_the_recorded_ones(self, case):
        g = FlowGraph.model_validate(case["result"])
        got = (_id(lane_tail(g, case["block"])),
               [e.id for e in loop_wires(g, case["block"])])
        assert got == (case["lane_tail"], case["loop_wires"]), case["id"]

    @pytest.mark.parametrize("case", CARRY_CASES, ids=lambda c: c["id"])
    def test_the_result_has_no_lane_refusal(self, case):
        assert lane_refusals(FlowGraph.model_validate(case["result"])) == [], \
            case["id"]

    @pytest.mark.parametrize("case", CARRY_CASES, ids=lambda c: c["id"])
    def test_the_result_is_the_connect_and_a_carry_nothing_more(self, case):
        """What a carry can make, held here as well as in the TypeScript: the
        graph plus the drawn wire, last, with nothing changed but the source
        of a pass wire into the block's ``next``, re-sourced to the recorded
        tail with its id and its place kept. A result recorded with a wire
        added, dropped or reordered, or a node edited, is no carry's.

        Mutant of the FIXTURE "the carried wire re-minted" (a scratch copy:
        case 1's carried wire recorded as ``loop2``) failed:
            FAILED ...::test_the_result_is_the_connect_and_a_carry_nothing_more[carry-autofocus-after-looped-cycle]
                AssertionError: carry-autofocus-after-looped-cycle: {'id': 'loop',
                'from': 'cy', 'fromPort': 'pass', 'to': 't', 'toPort': 'next'}
                became {'id': 'loop2', 'from': 'af', 'fromPort': 'pass', 'to': 't',
                'toPort': 'next'}, which no carry makes
            (2 failed, 30 passed: the recorded-columns case with it, assert ('af',
            ['loop2']) == ('af', ['loop'])).
        """
        before, after = case["graph"], case["result"]
        assert after["nodes"] == before["nodes"], case["id"]
        drawn = [*before["edges"], case["connect"]]
        assert len(after["edges"]) == len(drawn), case["id"]
        for was, now in zip(drawn, after["edges"]):
            carried = (was["fromPort"] == "pass" and was["to"] == case["block"]
                       and was["toPort"] == "next"
                       and now == {**was, "from": case["lane_tail"]})
            assert now == was or carried, (
                f"{case['id']}: {was} became {now}, which no carry makes")

    def test_the_fixture_holds_the_named_cases(self):
        """The TypeScript grades itself against these ids too."""
        assert {c["id"] for c in CARRY_CASES} >= {*CARRY_MOVES, *CARRY_CONTROLS}

    @pytest.mark.parametrize("case_id", CARRY_MOVES)
    def test_without_the_carry_the_mosaic_is_refused(self, case_id):
        """Premise of each moving case: the connect alone, the wire left
        where it was, leaves a pass wire mid-lane (M12), so a result that
        kept it fails ``test_the_result_has_no_lane_refusal``. That is #331:
        a stage appended, and the mosaic no longer runs."""
        case = _carry_case(case_id)
        moved = next(e for e in case["graph"]["edges"]
                     if e["id"] in case["loop_wires"])
        assert moved["from"] != case["lane_tail"], case_id
        assert [(r["code"], r["node_id"])
                for r in lane_refusals(_uncarried(case))] == \
            [("M12", moved["from"])], case_id

    @pytest.mark.parametrize("case_id", CARRY_CONTROLS)
    def test_a_control_is_the_connect_alone(self, case_id):
        """A 1x1 block, a lane with no loop wire and a stray pass wire move
        nothing (spec 1.4 item 4, "When it is deleted", M4): the connect's
        wire is added and every other wire is as it was.

        THE ONLY CHECK HERE THAT SEES A CONTROL RECORDED AS CARRIED. Mutant
        of the FIXTURE "the 1x1 control recorded as carried" (a scratch copy:
        carry-single-target-control's ``pw`` re-sourced to ``af`` in its
        result, ``loop_wires`` ["pw"]) failed:
            FAILED ...::test_a_control_is_the_connect_alone[carry-single-target-control]
                AssertionError: carry-single-target-control
                At index 1 diff: {'id': 'pw', 'from': 'af', 'fromPort': 'pass',
                'to': 't', 'toPort': 'next'} != {'id': 'pw', 'from': 'cy',
                'fromPort': 'pass', 'to': 't', 'toPort': 'next'}
            (1 failed, 37 passed of this class): a re-sourced pass wire is
            exactly what ``..._nothing_more`` lets a carry make, and one panel
            has no lane refusal to find, so nothing else here goes red.
        Mutant of the FIXTURE "the no-loop-wire control recorded with a loop
        added" (a ``pass`` wire from ``af`` into ``t.next`` appended to its
        result, ``loop_wires`` ["added"]) failed this case and
        ``..._nothing_more`` (assert 3 == 2), 2 failed, 36 passed. Both
        mutants also fail the case in panelLane.test.ts and
        flowsSlice.test.ts, whose carry makes the graph without the change.
        """
        case = _carry_case(case_id)
        assert case["result"]["edges"] == [*case["graph"]["edges"],
                                           case["connect"]], case_id

    def test_the_stranding_case_is_the_one_a_tail_only_carry_misses(self):
        """Case 2's stranding shape tells "any pass wire of the lane" from
        "the pre-connect tail's loop wire" only while the wire it carries
        leaves a stage that is NOT the tail the operator drew from. So its
        premises: the connect leaves the tail, the lane has no loop wire by
        ``loop_wires`` (the tail's), and the graph is already M12 at the
        cycle. (It is M13 at the CAPTURE too, which is unwired until the
        connect; only the M12 is this case's.)

        Mutant of the FIXTURE "the stranding case already looped" (a scratch
        copy: its ``loop`` wire drawn from ``af`` in graph and result alike,
        the holding case over again) failed:
            AssertionError: the stranding case's lane already has its loop wire on
            the tail, so a carry of the tail's loop wire alone passes it
            assert [FlowEdge(id=...oPort='next')] == []
              Left contains one more item: FlowEdge(id='loop', from_='af',
              fromPort='pass', to='t', toPort='next')
            (1 failed, 31 passed): only this premise sees a case that has stopped
            telling the two rules apart.
        """
        case = _carry_case("carry-capture-after-autofocus-stranding-the-loop")
        before = FlowGraph.model_validate(case["graph"])
        assert _id(lane_tail(before, "t")) == case["connect"]["from"]
        assert loop_wires(before, "t") == [], (
            "the stranding case's lane already has its loop wire on the tail, "
            "so a carry of the tail's loop wire alone passes it")
        assert [(r["code"], r["node_id"]) for r in lane_refusals(before)
                if r["code"] == "M12"] == [("M12", "cy")]

    def test_the_foreign_wire_control_is_one_a_wider_carry_would_break(self):
        """The foreign-wire control holds the other edge of "a stage of the
        lane": the carry widened for #331 to every pass wire into the block's
        ``next`` that leaves a stage of ITS lane, and no further. A pass wire
        from another TARGET's lane does nothing (M4), and carried to the new
        tail it would become this block's loop, a rotation nobody asked for
        (1.4: the wire "is never added as a side effect of connecting
        something else"). The control tells the two rules apart only while
        its stray wire leaves a stage another TARGET owns and carrying it
        changes what runs. So its premises: the stray wire's source is
        M33's, outside M31's lane; M31 has no loop wire before or after; and
        the graph a wider carry makes (the stray wire re-sourced to the new
        tail) is one compile.py reads as M31's loop.

        Mutant of flowsSlice.ts carryLoopWire "carry from any owned stage"
        (``lane.has(e.from)`` -> ``ownerOf(graph, e.from) !== null``, in a
        private scratch copy of ui/) passed all 31 panelLane.test.ts and all
        47 flowsSlice.test.ts cases before this control. With it, both fail
        on this case (panelLane.test: 30/32 passed, the identity control
        with it; flowsSlice.test: 47 passed, 1 failed): carryLoopWire made
        "stray:af.pass->t.next" where the fixture records
        "stray:c2.pass->t.next".

        Mutant of the FIXTURE "the stray wire is the block's own" (a scratch
        copy: the ``stray`` wire drawn from ``cy`` in graph and result, so it
        leaves this lane's first stage) failed:
            AssertionError: the stray wire leaves cy, a stage of M31's own
            lane, so the control no longer tells the lane from any owned
            stage
        (2 failed, 111 passed: test_the_result_has_no_lane_refusal for this
        case with it, since a pass wire from cy is M12 once the AUTOFOCUS
        follows it; panelLane.test.ts failed the case too, 30/32 passed).
        """
        case = _carry_case("carry-foreign-pass-wire-control")
        before = FlowGraph.model_validate(case["graph"])
        stray = next(e for e in before.edges
                     if e.fromPort == "pass" and e.to == case["block"])
        lane = {n.id for n in panel_lane(before, case["block"])}
        assert stray.from_ not in lane, (
            f"the stray wire leaves {stray.from_}, a stage of M31's own lane, "
            f"so the control no longer tells the lane from any owned stage")
        owner = owner_of(before, stray.from_)
        assert owner is not None and owner.id != case["block"], stray.from_
        assert loop_wires(before, case["block"]) == []
        wider = FlowGraph.model_validate({**case["result"], "edges": [
            {**e, "from": case["lane_tail"]} if e["id"] == stray.id else e
            for e in case["result"]["edges"]]})
        assert [e.id for e in loop_wires(wider, case["block"])] == [stray.id]
        loops = {t["node_id"]: t.get("loop") for t in compile_plan(
            FlowGraph.model_validate(case["result"]), "n")["targets"]}
        wider_loops = {t["node_id"]: t.get("loop")
                       for t in compile_plan(wider, "n")["targets"]}
        assert (loops[case["block"]], wider_loops[case["block"]]) == \
            (False, True)
